; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	au_create_spinlock
PUBLIC	au_remove_spinlock
EXTRN	kmalloc:PROC
EXTRN	kfree:PROC
pdata	SEGMENT
$pdata$au_create_spinlock DD imagerel $LN3
	DD	imagerel $LN3+41
	DD	imagerel $unwind$au_create_spinlock
$pdata$au_remove_spinlock DD imagerel $LN3
	DD	imagerel $LN3+24
	DD	imagerel $unwind$au_remove_spinlock
pdata	ENDS
xdata	SEGMENT
$unwind$au_create_spinlock DD 010401H
	DD	06204H
$unwind$au_remove_spinlock DD 010901H
	DD	04209H
xdata	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\atomic\au_spinlock.cpp
_TEXT	SEGMENT
spinlock$ = 48
au_remove_spinlock PROC

; 46   : void au_remove_spinlock(au_spinlock_t* spinlock) {

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 47   : 	kfree(spinlock);

	mov	rcx, QWORD PTR spinlock$[rsp]
	call	kfree

; 48   : }

	add	rsp, 40					; 00000028H
	ret	0
au_remove_spinlock ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\atomic\au_spinlock.cpp
_TEXT	SEGMENT
spinlock$ = 32
au_create_spinlock PROC

; 36   : au_spinlock_t * au_create_spinlock() {

$LN3:
	sub	rsp, 56					; 00000038H

; 37   : 	au_spinlock_t *spinlock = (au_spinlock_t*)kmalloc(sizeof(au_spinlock_t));

	mov	ecx, 8
	call	kmalloc
	mov	QWORD PTR spinlock$[rsp], rax

; 38   : 	spinlock->value = 0;

	mov	rax, QWORD PTR spinlock$[rsp]
	mov	QWORD PTR [rax], 0

; 39   : 	return spinlock;

	mov	rax, QWORD PTR spinlock$[rsp]

; 40   : }

	add	rsp, 56					; 00000038H
	ret	0
au_create_spinlock ENDP
_TEXT	ENDS
END
