; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_BSS	SEGMENT
print_lock DQ	01H DUP (?)
_BSS	ENDS
_DATA	SEGMENT
console_early DB 01H
_DATA	ENDS
PUBLIC	printf
EXTRN	?au_get_boot_info@@YAPEAU_AURORA_INFO_@@XZ:PROC	; au_get_boot_info
pdata	SEGMENT
$pdata$printf DD imagerel $LN4
	DD	imagerel $LN4+53
	DD	imagerel $unwind$printf
pdata	ENDS
xdata	SEGMENT
$unwind$printf DD 011801H
	DD	04218H
xdata	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\console.cpp
_TEXT	SEGMENT
text$ = 48
printf	PROC

; 40   : void printf(const char *text, ...) {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	sub	rsp, 40					; 00000028H

; 41   : 	//x64_lock_acquire(&print_lock);
; 42   : 	if (console_early) {

	movzx	eax, BYTE PTR console_early
	test	eax, eax
	je	SHORT $LN1@printf

; 43   : 		au_get_boot_info()->auprint(text);

	call	?au_get_boot_info@@YAPEAU_AURORA_INFO_@@XZ ; au_get_boot_info
	mov	rcx, QWORD PTR text$[rsp]
	call	QWORD PTR [rax+90]
$LN1@printf:

; 44   : 		//if (print_lock == 1)
; 45   : 		//	print_lock = 0;
; 46   : 		return;
; 47   : 	}
; 48   : 	//if (print_lock == 1)
; 49   : 	//	print_lock = 0;
; 50   : }

	add	rsp, 40					; 00000028H
	ret	0
printf	ENDP
_TEXT	ENDS
END
