; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?idtr@@3U_idtr@@A				; idtr
_BSS	SEGMENT
_fxsave_support DB 01H DUP (?)
	ALIGN	4

_avx_support DB	01H DUP (?)
	ALIGN	4

?idtr@@3U_idtr@@A DB 0aH DUP (?)			; idtr
_BSS	ENDS
CONST	SEGMENT
$SG3081	DB	'FXSAVE enabled', 0aH, 00H
$SG3084	DB	'[aurora]: SSE2 is supported ', 0aH, 00H
	ORG $+2
$SG3087	DB	'[aurora]: SSE3 is supported ', 0aH, 00H
	ORG $+2
$SG3099	DB	'CPU: Vendor -> %s ', 0aH, 00H
	ORG $+4
$SG3113	DB	'CPU: Brand = %s ', 0aH, 00H
	ORG $+6
$SG3118	DB	'Pit handler++', 0aH, 00H
	ORG $+1
$SG3041	DB	'[aurora]: Default interrupt++', 0aH, 00H
CONST	ENDS
PUBLIC	?x86_64_cpu_initialize@@YAX_N@Z			; x86_64_cpu_initialize
PUBLIC	x86_64_cpu_print_brand
PUBLIC	setvect
PUBLIC	?x86_64_setup_cpu_data@@YAXPEAX@Z		; x86_64_setup_cpu_data
PUBLIC	?x86_64_fxsave_supported@@YA_NXZ		; x86_64_fxsave_supported
PUBLIC	?x86_64_avx_supported@@YA_NXZ			; x86_64_avx_supported
PUBLIC	load_default_sregs
PUBLIC	?set_gdt_entry@@YAXAEAU_gdt@@_K1EE@Z		; set_gdt_entry
PUBLIC	?save_sregs@@YAXXZ				; save_sregs
PUBLIC	?x86_64_gdt_initialize@@YAXXZ			; x86_64_gdt_initialize
PUBLIC	interrupt_dispatcher
PUBLIC	?default_irq@@YAX_KPEAX@Z			; default_irq
PUBLIC	?x86_64_idt_initialize@@YAXXZ			; x86_64_idt_initialize
PUBLIC	?x86_64_cpu_feature_enable@@YAXXZ		; x86_64_cpu_feature_enable
PUBLIC	?pit_handler@@YAX_KPEAX@Z			; pit_handler
EXTRN	?au_get_boot_info@@YAPEAU_AURORA_INFO_@@XZ:PROC	; au_get_boot_info
EXTRN	x64_cli:PROC
EXTRN	x64_read_msr:PROC
EXTRN	x64_write_msr:PROC
EXTRN	x64_cpuid:PROC
EXTRN	x64_read_cr4:PROC
EXTRN	x64_write_cr4:PROC
EXTRN	x64_lgdt:PROC
EXTRN	x64_sgdt:PROC
EXTRN	printf:PROC
EXTRN	?x86_64_exception_init@@YAXXZ:PROC		; x86_64_exception_init
EXTRN	x86_64_pmmngr_alloc:PROC
EXTRN	?per_cpu_set_cpu_id@@YAXE@Z:PROC		; per_cpu_set_cpu_id
EXTRN	x86_64_phys_to_virt:PROC
EXTRN	?memset@@YAXPEAXEI@Z:PROC			; memset
EXTRN	x64_get_segment_register:PROC
EXTRN	x64_set_segment_register:PROC
EXTRN	x64_ltr:PROC
EXTRN	x64_lidt:PROC
EXTRN	default_irq_handlers:BYTE
_BSS	SEGMENT
	ALIGN	8

gdt	DQ	09H DUP (?)
the_gdtr DB	0aH DUP (?)
	ALIGN	4

old_gdtr DB	0aH DUP (?)
	ALIGN	4

oldsregs DW	08H DUP (?)
interrupts_handlers DQ 0100H DUP (?)
the_idt	DB	01000H DUP (?)
_BSS	ENDS
pdata	SEGMENT
$pdata$?x86_64_cpu_initialize@@YAX_N@Z DD imagerel $LN4
	DD	imagerel $LN4+248
	DD	imagerel $unwind$?x86_64_cpu_initialize@@YAX_N@Z
$pdata$x86_64_cpu_print_brand DD imagerel $LN3
	DD	imagerel $LN3+514
	DD	imagerel $unwind$x86_64_cpu_print_brand
$pdata$?x86_64_setup_cpu_data@@YAXPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+174
	DD	imagerel $unwind$?x86_64_setup_cpu_data@@YAXPEAX@Z
$pdata$load_default_sregs DD imagerel $LN3
	DD	imagerel $LN3+90
	DD	imagerel $unwind$load_default_sregs
$pdata$?set_gdt_entry@@YAXAEAU_gdt@@EE@Z DD imagerel ?set_gdt_entry@@YAXAEAU_gdt@@EE@Z
	DD	imagerel ?set_gdt_entry@@YAXAEAU_gdt@@EE@Z+82
	DD	imagerel $unwind$?set_gdt_entry@@YAXAEAU_gdt@@EE@Z
$pdata$?fill_gdt@@YAXPEAU_gdt@@@Z DD imagerel ?fill_gdt@@YAXPEAU_gdt@@@Z
	DD	imagerel ?fill_gdt@@YAXPEAU_gdt@@@Z+253
	DD	imagerel $unwind$?fill_gdt@@YAXPEAU_gdt@@@Z
$pdata$?save_sregs@@YAXXZ DD imagerel $LN6
	DD	imagerel $LN6+67
	DD	imagerel $unwind$?save_sregs@@YAXXZ
$pdata$?x86_64_gdt_initialize@@YAXXZ DD imagerel $LN3
	DD	imagerel $LN3+81
	DD	imagerel $unwind$?x86_64_gdt_initialize@@YAXXZ
$pdata$?register_irq@@YAXPEAU_idt@@PEAX@Z DD imagerel ?register_irq@@YAXPEAU_idt@@PEAX@Z
	DD	imagerel ?register_irq@@YAXPEAU_idt@@PEAX@Z+93
	DD	imagerel $unwind$?register_irq@@YAXPEAU_idt@@PEAX@Z
$pdata$interrupt_dispatcher DD imagerel $LN3
	DD	imagerel $LN3+45
	DD	imagerel $unwind$interrupt_dispatcher
$pdata$?default_irq@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+38
	DD	imagerel $unwind$?default_irq@@YAX_KPEAX@Z
$pdata$?x86_64_idt_initialize@@YAXXZ DD imagerel $LN12
	DD	imagerel $LN12+519
	DD	imagerel $unwind$?x86_64_idt_initialize@@YAXXZ
$pdata$?x86_64_cpu_feature_enable@@YAXXZ DD imagerel $LN10
	DD	imagerel $LN10+272
	DD	imagerel $unwind$?x86_64_cpu_feature_enable@@YAXXZ
$pdata$?pit_handler@@YAX_KPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+31
	DD	imagerel $unwind$?pit_handler@@YAX_KPEAX@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?x86_64_cpu_initialize@@YAX_N@Z DD 010801H
	DD	08208H
$unwind$x86_64_cpu_print_brand DD 020701H
	DD	0150107H
$unwind$?x86_64_setup_cpu_data@@YAXPEAX@Z DD 010901H
	DD	0c209H
$unwind$load_default_sregs DD 010401H
	DD	04204H
$unwind$?set_gdt_entry@@YAXAEAU_gdt@@EE@Z DD 011201H
	DD	06212H
$unwind$?fill_gdt@@YAXPEAU_gdt@@@Z DD 010901H
	DD	06209H
$unwind$?save_sregs@@YAXXZ DD 010401H
	DD	06204H
$unwind$?x86_64_gdt_initialize@@YAXXZ DD 010401H
	DD	04204H
$unwind$?register_irq@@YAXPEAU_idt@@PEAX@Z DD 010e01H
	DD	0220eH
$unwind$interrupt_dispatcher DD 010e01H
	DD	0420eH
$unwind$?default_irq@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?x86_64_idt_initialize@@YAXXZ DD 020701H
	DD	0a10107H
$unwind$?x86_64_cpu_feature_enable@@YAXXZ DD 010401H
	DD	0c204H
$unwind$?pit_handler@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
xdata	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?pit_handler@@YAX_KPEAX@Z PROC				; pit_handler

; 289  : void pit_handler(size_t v, void* p) {

$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 290  : 	printf("Pit handler++\n");

	lea	rcx, OFFSET FLAT:$SG3118
	call	printf

; 291  : 	
; 292  : }

	add	rsp, 40					; 00000028H
	ret	0
?pit_handler@@YAX_KPEAX@Z ENDP				; pit_handler
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
cr4$1 = 48
cr4$2 = 56
d$ = 64
c$ = 72
b$ = 80
a$ = 88
?x86_64_cpu_feature_enable@@YAXXZ PROC			; x86_64_cpu_feature_enable

; 207  : void x86_64_cpu_feature_enable() {

$LN10:
	sub	rsp, 104				; 00000068H

; 208  : 
; 209  : 	size_t a, b, c, d;
; 210  : 	x64_cpuid(1, &a, &b, &c, &d);

	mov	QWORD PTR [rsp+40], 0
	lea	rax, QWORD PTR d$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR c$[rsp]
	lea	r8, QWORD PTR b$[rsp]
	lea	rdx, QWORD PTR a$[rsp]
	mov	ecx, 1
	call	x64_cpuid

; 211  : 
; 212  : 	if ((c & (1 << 26)) != 0) {

	mov	rax, QWORD PTR c$[rsp]
	and	rax, 67108864				; 04000000H
	test	rax, rax
	je	SHORT $LN7@x86_64_cpu

; 213  : 		/* Enable XCR0 register */
; 214  : 		uint64_t cr4 = x64_read_cr4();

	call	x64_read_cr4
	mov	QWORD PTR cr4$2[rsp], rax

; 215  : 		cr4 |= (1 << 18);

	mov	rax, QWORD PTR cr4$2[rsp]
	bts	rax, 18
	mov	QWORD PTR cr4$2[rsp], rax

; 216  : 		x64_write_cr4(cr4);

	mov	rcx, QWORD PTR cr4$2[rsp]
	call	x64_write_cr4
$LN7@x86_64_cpu:

; 217  : 	}
; 218  : 
; 219  : 	if ((d & (1 << 25)) != 0){

	mov	rax, QWORD PTR d$[rsp]
	and	rax, 33554432				; 02000000H
	test	rax, rax
	je	SHORT $LN6@x86_64_cpu

; 220  : 		size_t cr4 = x64_read_cr4();

	call	x64_read_cr4
	mov	QWORD PTR cr4$1[rsp], rax

; 221  : 		cr4 |= (1 << 10);

	mov	rax, QWORD PTR cr4$1[rsp]
	bts	rax, 10
	mov	QWORD PTR cr4$1[rsp], rax

; 222  : 
; 223  : 		if ((d & (1 << 24)) != 0) {

	mov	rax, QWORD PTR d$[rsp]
	and	rax, 16777216				; 01000000H
	test	rax, rax
	je	SHORT $LN5@x86_64_cpu

; 224  : 			cr4 |= (1 << 9);

	mov	rax, QWORD PTR cr4$1[rsp]
	bts	rax, 9
	mov	QWORD PTR cr4$1[rsp], rax

; 225  : 			au_get_boot_info()->auprint("FXSAVE enabled\n");

	call	?au_get_boot_info@@YAPEAU_AURORA_INFO_@@XZ ; au_get_boot_info
	lea	rcx, OFFSET FLAT:$SG3081
	call	QWORD PTR [rax+90]

; 226  : 			_fxsave_support = true;

	mov	BYTE PTR _fxsave_support, 1
$LN5@x86_64_cpu:

; 227  : 		}
; 228  : 
; 229  : 		x64_write_cr4(cr4);

	mov	rcx, QWORD PTR cr4$1[rsp]
	call	x64_write_cr4
	jmp	SHORT $LN4@x86_64_cpu
$LN6@x86_64_cpu:

; 230  : 	}
; 231  : 	else if ((d & (1 << 26)) != 0) {

	mov	rax, QWORD PTR d$[rsp]
	and	rax, 67108864				; 04000000H
	test	rax, rax
	je	SHORT $LN3@x86_64_cpu

; 232  : 		au_get_boot_info()->auprint("[aurora]: SSE2 is supported \n");

	call	?au_get_boot_info@@YAPEAU_AURORA_INFO_@@XZ ; au_get_boot_info
	lea	rcx, OFFSET FLAT:$SG3084
	call	QWORD PTR [rax+90]
	jmp	SHORT $LN2@x86_64_cpu
$LN3@x86_64_cpu:

; 233  : 	}
; 234  : 	else if ((c & (1 << 0)) != 0)

	mov	rax, QWORD PTR c$[rsp]
	and	rax, 1
	test	rax, rax
	je	SHORT $LN1@x86_64_cpu

; 235  : 		au_get_boot_info()->auprint("[aurora]: SSE3 is supported \n");

	call	?au_get_boot_info@@YAPEAU_AURORA_INFO_@@XZ ; au_get_boot_info
	lea	rcx, OFFSET FLAT:$SG3087
	call	QWORD PTR [rax+90]
$LN1@x86_64_cpu:
$LN2@x86_64_cpu:
$LN4@x86_64_cpu:

; 236  : 
; 237  : #ifdef AVX_ENABLED
; 238  : 	if ((c & (1 << 28)) != 0) {
; 239  : 		size_t xcr0 = x64_read_xcr0();
; 240  : 		xcr0 |= 7;
; 241  : 		x64_write_xcr0(xcr0);
; 242  : 	}
; 243  : 	x64_cpuid(0xD, &a, &b, &c, &d);
; 244  : 	if ((a & (7 << 5)) != 0) {
; 245  : 		size_t ax, bx, cx, dx;
; 246  : 		x64_cpuid(0xD, &ax, &bx, &cx, &dx, 0);
; 247  : 		size_t xcr0 = x64_read_xcr0();
; 248  : 		xcr0 |= (ax&(7<<5));
; 249  : 		x64_write_xcr0(xcr0);
; 250  : 	}
; 251  : #endif
; 252  : }

	add	rsp, 104				; 00000068H
	ret	0
?x86_64_cpu_feature_enable@@YAXXZ ENDP			; x86_64_cpu_feature_enable
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
n$1 = 48
i$2 = 52
i$3 = 56
thegdt$ = 64
tv166 = 72
curr_gdt$ = 80
m_ist$ = 96
tss$ = 128
bos$4 = 240
?x86_64_idt_initialize@@YAXXZ PROC			; x86_64_idt_initialize

; 171  : void x86_64_idt_initialize() {

$LN12:
	sub	rsp, 1288				; 00000508H

; 172  : 
; 173  : 
; 174  : 	void* m_ist[4];
; 175  : 	uint32_t tss[28];
; 176  : 	for (int i = 0; i < 28; i++) tss[i] = 0xffffffff;

	mov	DWORD PTR i$3[rsp], 0
	jmp	SHORT $LN9@x86_64_idt
$LN8@x86_64_idt:
	mov	eax, DWORD PTR i$3[rsp]
	inc	eax
	mov	DWORD PTR i$3[rsp], eax
$LN9@x86_64_idt:
	cmp	DWORD PTR i$3[rsp], 28
	jge	SHORT $LN7@x86_64_idt
	movsxd	rax, DWORD PTR i$3[rsp]
	mov	DWORD PTR tss$[rsp+rax*4], -1		; ffffffffH
	jmp	SHORT $LN8@x86_64_idt
$LN7@x86_64_idt:

; 177  : 	for (int i = 0; i < 1; i++)

	mov	DWORD PTR i$2[rsp], 0
	jmp	SHORT $LN6@x86_64_idt
$LN5@x86_64_idt:
	mov	eax, DWORD PTR i$2[rsp]
	inc	eax
	mov	DWORD PTR i$2[rsp], eax
$LN6@x86_64_idt:
	cmp	DWORD PTR i$2[rsp], 1
	jge	SHORT $LN4@x86_64_idt

; 178  : 	{
; 179  : 		uint8_t bos[1024];
; 180  : 		m_ist[i] = bos + 1024;

	lea	rax, QWORD PTR bos$4[rsp+1024]
	movsxd	rcx, DWORD PTR i$2[rsp]
	mov	QWORD PTR m_ist$[rsp+rcx*8], rax

; 181  : 		tss[9 + i * 2] = reinterpret_cast<uint64_t>(m_ist[i]) & 0xffffffff;

	movsxd	rax, DWORD PTR i$2[rsp]
	mov	ecx, -1					; ffffffffH
	mov	rax, QWORD PTR m_ist$[rsp+rax*8]
	and	rax, rcx
	mov	ecx, DWORD PTR i$2[rsp]
	lea	ecx, DWORD PTR [rcx+rcx+9]
	movsxd	rcx, ecx
	mov	DWORD PTR tss$[rsp+rcx*4], eax

; 182  : 		tss[9 + i * 2 + 1] = reinterpret_cast<uint64_t>(m_ist[i]) >> 32;

	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rax, QWORD PTR m_ist$[rsp+rax*8]
	shr	rax, 32					; 00000020H
	mov	ecx, DWORD PTR i$2[rsp]
	lea	ecx, DWORD PTR [rcx+rcx+10]
	movsxd	rcx, ecx
	mov	DWORD PTR tss$[rsp+rcx*4], eax

; 183  : 	}

	jmp	SHORT $LN5@x86_64_idt
$LN4@x86_64_idt:

; 184  : 	gdtr curr_gdt;
; 185  : 	x64_sgdt(&curr_gdt);

	lea	rcx, QWORD PTR curr_gdt$[rsp]
	call	x64_sgdt

; 186  : 	gdt_entry* thegdt = the_gdtr.gdtaddr; //curr_gdt.gdtaddr;

	mov	rax, QWORD PTR the_gdtr+2
	mov	QWORD PTR thegdt$[rsp], rax

; 187  : 	set_gdt_entry(thegdt[GDT_ENTRY_TSS], reinterpret_cast<uint64_t>(tss)& UINT32_MAX, sizeof(tss), GDT_ACCESS_PRESENT | 0x9, 0);

	lea	rax, QWORD PTR tss$[rsp]
	mov	ecx, -1					; ffffffffH
	and	rax, rcx
	mov	ecx, 8
	imul	rcx, rcx, 7
	mov	rdx, QWORD PTR thegdt$[rsp]
	add	rdx, rcx
	mov	rcx, rdx
	mov	BYTE PTR [rsp+32], 0
	mov	r9b, 137				; 00000089H
	mov	r8d, 112				; 00000070H
	mov	rdx, rax
	call	?set_gdt_entry@@YAXAEAU_gdt@@_K1EE@Z	; set_gdt_entry

; 188  : 	*(uint64_t*)&thegdt[GDT_ENTRY_TSS + 1] = (reinterpret_cast<uint64_t>(tss) >> 32);

	lea	rax, QWORD PTR tss$[rsp]
	shr	rax, 32					; 00000020H
	mov	ecx, 8
	imul	rcx, rcx, 8
	mov	rdx, QWORD PTR thegdt$[rsp]
	mov	QWORD PTR [rdx+rcx], rax

; 189  : 	x64_ltr(SEGVAL(GDT_ENTRY_TSS, 0));

	mov	cx, 56					; 00000038H
	call	x64_ltr

; 190  : 
; 191  : 
; 192  : 	//IDTR *idtr = (IDTR*)0xFFFFD80000000000;
; 193  : 	idtr.idtaddr = the_idt;

	lea	rax, OFFSET FLAT:the_idt
	mov	QWORD PTR ?idtr@@3U_idtr@@A+2, rax

; 194  : 	idtr.length = 256 * sizeof(IDT)-1;

	mov	eax, 4095				; 00000fffH
	mov	WORD PTR ?idtr@@3U_idtr@@A, ax

; 195  : 	x64_lidt(&idtr);

	lea	rcx, OFFSET FLAT:?idtr@@3U_idtr@@A	; idtr
	call	x64_lidt

; 196  : 	for (int n = 0; n < 256; n++)

	mov	DWORD PTR n$1[rsp], 0
	jmp	SHORT $LN3@x86_64_idt
$LN2@x86_64_idt:
	mov	eax, DWORD PTR n$1[rsp]
	inc	eax
	mov	DWORD PTR n$1[rsp], eax
$LN3@x86_64_idt:
	cmp	DWORD PTR n$1[rsp], 256			; 00000100H
	jge	$LN1@x86_64_idt

; 197  : 	{
; 198  : 		the_idt[n].ist = 0;

	movsxd	rax, DWORD PTR n$1[rsp]
	imul	rax, rax, 16
	lea	rcx, OFFSET FLAT:the_idt
	mov	BYTE PTR [rcx+rax+4], 0

; 199  : 		the_idt[n].selector = SEGVAL(GDT_ENTRY_KERNEL_CODE, 0);

	movsxd	rax, DWORD PTR n$1[rsp]
	imul	rax, rax, 16
	lea	rcx, OFFSET FLAT:the_idt
	mov	edx, 8
	mov	WORD PTR [rcx+rax+2], dx

; 200  : 		the_idt[n].zero = 0;

	movsxd	rax, DWORD PTR n$1[rsp]
	imul	rax, rax, 16
	lea	rcx, OFFSET FLAT:the_idt
	mov	DWORD PTR [rcx+rax+12], 0

; 201  : 		the_idt[n].type_attr = GDT_ACCESS_PRESENT | 0xE;

	movsxd	rax, DWORD PTR n$1[rsp]
	imul	rax, rax, 16
	lea	rcx, OFFSET FLAT:the_idt
	mov	BYTE PTR [rcx+rax+5], 142		; 0000008eH

; 202  : 		register_irq(&the_idt[n], default_irq_handlers[n]);

	movsxd	rax, DWORD PTR n$1[rsp]
	lea	rcx, OFFSET FLAT:default_irq_handlers
	movsxd	rdx, DWORD PTR n$1[rsp]
	imul	rdx, rdx, 16
	lea	r8, OFFSET FLAT:the_idt
	add	r8, rdx
	mov	rdx, r8
	mov	QWORD PTR tv166[rsp], rdx
	mov	rdx, QWORD PTR [rcx+rax*8]
	mov	rax, QWORD PTR tv166[rsp]
	mov	rcx, rax
	call	?register_irq@@YAXPEAU_idt@@PEAX@Z	; register_irq

; 203  : 	}

	jmp	$LN2@x86_64_idt
$LN1@x86_64_idt:

; 204  : 
; 205  : }

	add	rsp, 1288				; 00000508H
	ret	0
?x86_64_idt_initialize@@YAXXZ ENDP			; x86_64_idt_initialize
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
vect$ = 48
param$ = 56
?default_irq@@YAX_KPEAX@Z PROC				; default_irq

; 164  : void default_irq(size_t vect, void* param){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 165  : 	x64_cli();

	call	x64_cli

; 166  : 	printf("[aurora]: Default interrupt++\n");

	lea	rcx, OFFSET FLAT:$SG3041
	call	printf
$LN2@default_ir:

; 167  : 	for (;;);

	jmp	SHORT $LN2@default_ir

; 168  : }

	add	rsp, 40					; 00000028H
	ret	0
?default_irq@@YAX_KPEAX@Z ENDP				; default_irq
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
num$ = 48
frame$ = 56
interrupt_dispatcher PROC

; 156  : {

$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 157  : 	interrupts_handlers[num](num, frame);

	lea	rax, OFFSET FLAT:interrupts_handlers
	mov	rdx, QWORD PTR frame$[rsp]
	mov	rcx, QWORD PTR num$[rsp]
	mov	r8, QWORD PTR num$[rsp]
	call	QWORD PTR [rax+r8*8]

; 158  : 	return;
; 159  : }

	add	rsp, 40					; 00000028H
	ret	0
interrupt_dispatcher ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
faddr$ = 0
entry$ = 32
function$ = 40
?register_irq@@YAXPEAU_idt@@PEAX@Z PROC			; register_irq

; 143  : {

	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24

; 144  : 	size_t faddr = (size_t)function;

	mov	rax, QWORD PTR function$[rsp]
	mov	QWORD PTR faddr$[rsp], rax

; 145  : 	entry->offset_1 = faddr & UINT16_MAX;

	mov	rax, QWORD PTR faddr$[rsp]
	and	rax, 65535				; 0000ffffH
	mov	rcx, QWORD PTR entry$[rsp]
	mov	WORD PTR [rcx], ax

; 146  : 	entry->offset_2 = (faddr >> 16) & UINT16_MAX;

	mov	rax, QWORD PTR faddr$[rsp]
	shr	rax, 16
	and	rax, 65535				; 0000ffffH
	mov	rcx, QWORD PTR entry$[rsp]
	mov	WORD PTR [rcx+6], ax

; 147  : 	entry->offset_3 = (faddr >> 32) & UINT32_MAX;

	mov	rax, QWORD PTR faddr$[rsp]
	shr	rax, 32					; 00000020H
	mov	ecx, -1					; ffffffffH
	and	rax, rcx
	mov	rcx, QWORD PTR entry$[rsp]
	mov	DWORD PTR [rcx+8], eax

; 148  : }

	add	rsp, 24
	ret	0
?register_irq@@YAXPEAU_idt@@PEAX@Z ENDP			; register_irq
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
?x86_64_gdt_initialize@@YAXXZ PROC			; x86_64_gdt_initialize

; 124  : {

$LN3:
	sub	rsp, 40					; 00000028H

; 125  : 	x64_sgdt(&old_gdtr);

	lea	rcx, OFFSET FLAT:old_gdtr
	call	x64_sgdt

; 126  : 	save_sregs();

	call	?save_sregs@@YAXXZ			; save_sregs

; 127  : 	fill_gdt(gdt);

	lea	rcx, OFFSET FLAT:gdt
	call	?fill_gdt@@YAXPEAU_gdt@@@Z		; fill_gdt

; 128  : 	the_gdtr.gdtaddr = gdt;

	lea	rax, OFFSET FLAT:gdt
	mov	QWORD PTR the_gdtr+2, rax

; 129  : 	the_gdtr.size = GDT_ENTRIES * sizeof(gdt_entry)-1;

	mov	eax, 71					; 00000047H
	mov	WORD PTR the_gdtr, ax

; 130  : 	x64_lgdt(&the_gdtr);

	lea	rcx, OFFSET FLAT:the_gdtr
	call	x64_lgdt

; 131  : 	load_default_sregs();

	call	load_default_sregs

; 132  : }

	add	rsp, 40					; 00000028H
	ret	0
?x86_64_gdt_initialize@@YAXXZ ENDP			; x86_64_gdt_initialize
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
reg$1 = 32
?save_sregs@@YAXXZ PROC					; save_sregs

; 106  : {

$LN6:
	sub	rsp, 56					; 00000038H

; 107  : 	for (uint_fast8_t reg = 0; reg < 8; ++reg)

	mov	BYTE PTR reg$1[rsp], 0
	jmp	SHORT $LN3@save_sregs
$LN2@save_sregs:
	movzx	eax, BYTE PTR reg$1[rsp]
	inc	al
	mov	BYTE PTR reg$1[rsp], al
$LN3@save_sregs:
	movzx	eax, BYTE PTR reg$1[rsp]
	cmp	eax, 8
	jge	SHORT $LN1@save_sregs

; 108  : 		oldsregs[reg] = x64_get_segment_register(reg);

	movzx	eax, BYTE PTR reg$1[rsp]
	mov	ecx, eax
	call	x64_get_segment_register
	movzx	ecx, BYTE PTR reg$1[rsp]
	lea	rdx, OFFSET FLAT:oldsregs
	mov	WORD PTR [rdx+rcx*2], ax
	jmp	SHORT $LN2@save_sregs
$LN1@save_sregs:

; 109  : }

	add	rsp, 56					; 00000038H
	ret	0
?save_sregs@@YAXXZ ENDP					; save_sregs
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
thegdt$ = 64
?fill_gdt@@YAXPEAU_gdt@@@Z PROC				; fill_gdt

; 89   : {

	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 90   : 	set_gdt_entry(thegdt[GDT_ENTRY_NULL], 0, 0, 0, 0);    //0x00

	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR thegdt$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	BYTE PTR [rsp+32], 0
	xor	r9d, r9d
	xor	r8d, r8d
	xor	edx, edx
	mov	rcx, rax
	call	?set_gdt_entry@@YAXAEAU_gdt@@_K1EE@Z	; set_gdt_entry

; 91   : 	//Kernel Code segment: STAR.SYSCALL_CS
; 92   : 	set_gdt_entry(thegdt[GDT_ENTRY_KERNEL_CODE], GDT_ACCESS_PRIVL(0) | GDT_ACCESS_RW | GDT_ACCESS_EX, GDT_FLAG_64BT);  //0x08

	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR thegdt$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	r8b, 2
	mov	dl, 10
	mov	rcx, rax
	call	?set_gdt_entry@@YAXAEAU_gdt@@EE@Z	; set_gdt_entry

; 93   : 	//Kernel Data segment
; 94   : 	set_gdt_entry(thegdt[GDT_ENTRY_KERNEL_DATA], GDT_ACCESS_PRIVL(0) | GDT_ACCESS_RW, GDT_FLAG_32BT);    //0x10

	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR thegdt$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	r8b, 4
	mov	dl, 2
	mov	rcx, rax
	call	?set_gdt_entry@@YAXAEAU_gdt@@EE@Z	; set_gdt_entry

; 95   : 	//User Code segment (32 bit): STAR.SYSRET_CS
; 96   : 	set_gdt_entry(thegdt[GDT_ENTRY_USER_CODE32], GDT_ACCESS_PRIVL(3) | GDT_ACCESS_RW | GDT_ACCESS_EX, GDT_FLAG_32BT);  //0x18

	mov	eax, 8
	imul	rax, rax, 3
	mov	rcx, QWORD PTR thegdt$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	r8b, 4
	mov	dl, 106					; 0000006aH
	mov	rcx, rax
	call	?set_gdt_entry@@YAXAEAU_gdt@@EE@Z	; set_gdt_entry

; 97   : 	//User Data segment
; 98   : 	set_gdt_entry(thegdt[GDT_ENTRY_USER_DATA], GDT_ACCESS_PRIVL(3) | GDT_ACCESS_RW, GDT_FLAG_32BT);    //0x20

	mov	eax, 8
	imul	rax, rax, 4
	mov	rcx, QWORD PTR thegdt$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	r8b, 4
	mov	dl, 98					; 00000062H
	mov	rcx, rax
	call	?set_gdt_entry@@YAXAEAU_gdt@@EE@Z	; set_gdt_entry

; 99   : 	//User Code segment (64 bit)
; 100  : 	set_gdt_entry(thegdt[GDT_ENTRY_USER_CODE], GDT_ACCESS_PRIVL(3) | GDT_ACCESS_RW | GDT_ACCESS_EX, GDT_FLAG_64BT);   //0x28  | 3 -- 0x2B

	mov	eax, 8
	imul	rax, rax, 5
	mov	rcx, QWORD PTR thegdt$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	r8b, 2
	mov	dl, 106					; 0000006aH
	mov	rcx, rax
	call	?set_gdt_entry@@YAXAEAU_gdt@@EE@Z	; set_gdt_entry

; 101  : 	//Kernel Code segment (32 bit)
; 102  : 	set_gdt_entry(thegdt[GDT_ENTRY_KERNEL_CODE32], GDT_ACCESS_PRIVL(3) | GDT_ACCESS_RW | GDT_ACCESS_EX, GDT_FLAG_32BT);  //0x30

	mov	eax, 8
	imul	rax, rax, 6
	mov	rcx, QWORD PTR thegdt$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	r8b, 4
	mov	dl, 106					; 0000006aH
	mov	rcx, rax
	call	?set_gdt_entry@@YAXAEAU_gdt@@EE@Z	; set_gdt_entry

; 103  : }

	add	rsp, 56					; 00000038H
	ret	0
?fill_gdt@@YAXPEAU_gdt@@@Z ENDP				; fill_gdt
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
entry$ = 64
access$ = 72
flags$ = 80
?set_gdt_entry@@YAXAEAU_gdt@@EE@Z PROC			; set_gdt_entry

; 82   : {

	mov	BYTE PTR [rsp+24], r8b
	mov	BYTE PTR [rsp+16], dl
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 83   : 	access |= GDT_ACCESS_PRESENT | GDT_ACCESS_TYPE;

	movzx	eax, BYTE PTR access$[rsp]
	or	eax, 144				; 00000090H
	mov	BYTE PTR access$[rsp], al

; 84   : 	flags |= GDT_FLAG_GRAN;

	movzx	eax, BYTE PTR flags$[rsp]
	or	eax, 8
	mov	BYTE PTR flags$[rsp], al

; 85   : 	set_gdt_entry(entry, 0, SIZE_MAX, access, flags);

	movzx	eax, BYTE PTR flags$[rsp]
	mov	BYTE PTR [rsp+32], al
	movzx	r9d, BYTE PTR access$[rsp]
	mov	r8d, -1					; ffffffffH
	xor	edx, edx
	mov	rcx, QWORD PTR entry$[rsp]
	call	?set_gdt_entry@@YAXAEAU_gdt@@_K1EE@Z	; set_gdt_entry

; 86   : }

	add	rsp, 56					; 00000038H
	ret	0
?set_gdt_entry@@YAXAEAU_gdt@@EE@Z ENDP			; set_gdt_entry
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
entry$ = 8
base$ = 16
limit$ = 24
access$ = 32
flags$ = 40
?set_gdt_entry@@YAXAEAU_gdt@@_K1EE@Z PROC		; set_gdt_entry

; 72   : {

	mov	BYTE PTR [rsp+32], r9b
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx

; 73   : 	entry.base_low = base & 0xFFFF;

	mov	rax, QWORD PTR base$[rsp]
	and	rax, 65535				; 0000ffffH
	mov	rcx, QWORD PTR entry$[rsp]
	mov	WORD PTR [rcx+2], ax

; 74   : 	entry.base_mid = (base >> 16) & 0xFF;

	mov	rax, QWORD PTR base$[rsp]
	shr	rax, 16
	and	rax, 255				; 000000ffH
	mov	rcx, QWORD PTR entry$[rsp]
	mov	BYTE PTR [rcx+4], al

; 75   : 	entry.base_high = (base >> 24) & 0xFF;

	mov	rax, QWORD PTR base$[rsp]
	shr	rax, 24
	and	rax, 255				; 000000ffH
	mov	rcx, QWORD PTR entry$[rsp]
	mov	BYTE PTR [rcx+7], al

; 76   : 	entry.limit_low = limit & 0xFFFF;

	mov	rax, QWORD PTR limit$[rsp]
	and	rax, 65535				; 0000ffffH
	mov	rcx, QWORD PTR entry$[rsp]
	mov	WORD PTR [rcx], ax

; 77   : 	entry.access = access;

	mov	rax, QWORD PTR entry$[rsp]
	movzx	ecx, BYTE PTR access$[rsp]
	mov	BYTE PTR [rax+5], cl

; 78   : 	entry.flags_limit = (flags << 4) | ((limit >> 16) & 0xF);

	movzx	eax, BYTE PTR flags$[rsp]
	shl	eax, 4
	cdqe
	mov	rcx, QWORD PTR limit$[rsp]
	shr	rcx, 16
	and	rcx, 15
	or	rax, rcx
	mov	rcx, QWORD PTR entry$[rsp]
	mov	BYTE PTR [rcx+6], al

; 79   : }

	ret	0
?set_gdt_entry@@YAXAEAU_gdt@@_K1EE@Z ENDP		; set_gdt_entry
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
load_default_sregs PROC

; 112  : {

$LN3:
	sub	rsp, 40					; 00000028H

; 113  : 	x64_set_segment_register(SREG_CS, SEGVAL(GDT_ENTRY_KERNEL_CODE, 0));

	mov	dx, 8
	xor	ecx, ecx
	call	x64_set_segment_register

; 114  : 	x64_set_segment_register(SREG_DS, SEGVAL(GDT_ENTRY_KERNEL_DATA, 0));

	mov	dx, 16
	mov	ecx, 1
	call	x64_set_segment_register

; 115  : 	x64_set_segment_register(SREG_ES, SEGVAL(GDT_ENTRY_KERNEL_DATA, 0));

	mov	dx, 16
	mov	ecx, 2
	call	x64_set_segment_register

; 116  : 	x64_set_segment_register(SREG_SS, SEGVAL(GDT_ENTRY_KERNEL_DATA, 0));

	mov	dx, 16
	mov	ecx, 5
	call	x64_set_segment_register

; 117  : 	//Per CPU data
; 118  : 	x64_set_segment_register(SREG_FS, SEGVAL(GDT_ENTRY_KERNEL_DATA, 0));

	mov	dx, 16
	mov	ecx, 3
	call	x64_set_segment_register

; 119  : 	x64_set_segment_register(SREG_GS, SEGVAL(GDT_ENTRY_KERNEL_DATA, 0));

	mov	dx, 16
	mov	ecx, 4
	call	x64_set_segment_register

; 120  : }

	add	rsp, 40					; 00000028H
	ret	0
load_default_sregs ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
?x86_64_avx_supported@@YA_NXZ PROC			; x86_64_avx_supported

; 358  : 	return _avx_support;

	movzx	eax, BYTE PTR _avx_support

; 359  : }

	ret	0
?x86_64_avx_supported@@YA_NXZ ENDP			; x86_64_avx_supported
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
?x86_64_fxsave_supported@@YA_NXZ PROC			; x86_64_fxsave_supported

; 351  : 	return _fxsave_support;

	movzx	eax, BYTE PTR _fxsave_support

; 352  : }

	ret	0
?x86_64_fxsave_supported@@YA_NXZ ENDP			; x86_64_fxsave_supported
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
b$ = 48
cpu$1 = 56
d$ = 64
c$ = 72
a$ = 80
data$ = 112
?x86_64_setup_cpu_data@@YAXPEAX@Z PROC			; x86_64_setup_cpu_data

; 331  : void x86_64_setup_cpu_data(void* data) {

$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 104				; 00000068H

; 332  : 
; 333  : 	size_t a, b, c, d;
; 334  : 	x64_cpuid(0x1, &a, &b, &c, &d);

	mov	QWORD PTR [rsp+40], 0
	lea	rax, QWORD PTR d$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR c$[rsp]
	lea	r8, QWORD PTR b$[rsp]
	lea	rdx, QWORD PTR a$[rsp]
	mov	ecx, 1
	call	x64_cpuid

; 335  : 	if ((b >> 24) == 0) {

	mov	rax, QWORD PTR b$[rsp]
	shr	rax, 24
	test	rax, rax
	jne	SHORT $LN2@x86_64_set

; 336  : 		cpu_t *cpu = (cpu_t*)x86_64_phys_to_virt((size_t)x86_64_pmmngr_alloc());

	call	x86_64_pmmngr_alloc
	mov	rcx, rax
	call	x86_64_phys_to_virt
	mov	QWORD PTR cpu$1[rsp], rax

; 337  : 		memset(cpu, 0, 4096);

	mov	r8d, 4096				; 00001000H
	xor	edx, edx
	mov	rcx, QWORD PTR cpu$1[rsp]
	call	?memset@@YAXPEAXEI@Z			; memset

; 338  : 		x64_write_msr(MSR_IA32_GS_BASE, (uint64_t)cpu);

	mov	rdx, QWORD PTR cpu$1[rsp]
	mov	ecx, -1073741567			; c0000101H
	call	x64_write_msr

; 339  : 		per_cpu_set_cpu_id((b >> 24));

	mov	rax, QWORD PTR b$[rsp]
	shr	rax, 24
	movzx	ecx, al
	call	?per_cpu_set_cpu_id@@YAXE@Z		; per_cpu_set_cpu_id

; 340  : 	}
; 341  : 	else {

	jmp	SHORT $LN1@x86_64_set
$LN2@x86_64_set:

; 342  : 		x64_write_msr(MSR_IA32_GS_BASE, (uint64_t)data);

	mov	rdx, QWORD PTR data$[rsp]
	mov	ecx, -1073741567			; c0000101H
	call	x64_write_msr

; 343  : 		per_cpu_set_cpu_id((b >> 24));

	mov	rax, QWORD PTR b$[rsp]
	shr	rax, 24
	movzx	ecx, al
	call	?per_cpu_set_cpu_id@@YAXE@Z		; per_cpu_set_cpu_id
$LN1@x86_64_set:

; 344  : 	}
; 345  : }

	add	rsp, 104				; 00000068H
	ret	0
?x86_64_setup_cpu_data@@YAXPEAX@Z ENDP			; x86_64_setup_cpu_data
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
vector$ = 8
function$ = 16
setvect	PROC

; 151  : {

	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx

; 152  : 	interrupts_handlers[vector] = function;

	lea	rax, OFFSET FLAT:interrupts_handlers
	mov	rcx, QWORD PTR vector$[rsp]
	mov	rdx, QWORD PTR function$[rsp]
	mov	QWORD PTR [rax+rcx*8], rdx

; 153  : };

	ret	0
setvect	ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
c$ = 48
b$ = 56
d$ = 64
a$ = 72
vendor$ = 80
bandstring$ = 96
maxcpuid$ = 152
x86_64_cpu_print_brand PROC

; 258  : void x86_64_cpu_print_brand() {

$LN3:
	sub	rsp, 168				; 000000a8H

; 259  : 	size_t maxcpuid, a, b, c, d;
; 260  : 	x64_cpuid(0, &maxcpuid, &b, &c, &d);

	mov	QWORD PTR [rsp+40], 0
	lea	rax, QWORD PTR d$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR c$[rsp]
	lea	r8, QWORD PTR b$[rsp]
	lea	rdx, QWORD PTR maxcpuid$[rsp]
	xor	ecx, ecx
	call	x64_cpuid

; 261  : 	char vendor[13];
; 262  : 	*(uint32_t*)&vendor[0] = b;

	mov	eax, 1
	imul	rax, rax, 0
	mov	ecx, DWORD PTR b$[rsp]
	mov	DWORD PTR vendor$[rsp+rax], ecx

; 263  : 	*(uint32_t*)&vendor[4] = d;

	mov	eax, 1
	imul	rax, rax, 4
	mov	ecx, DWORD PTR d$[rsp]
	mov	DWORD PTR vendor$[rsp+rax], ecx

; 264  : 	*(uint32_t*)&vendor[8] = c;

	mov	eax, 1
	imul	rax, rax, 8
	mov	ecx, DWORD PTR c$[rsp]
	mov	DWORD PTR vendor$[rsp+rax], ecx

; 265  : 	vendor[12] = 0;

	mov	eax, 1
	imul	rax, rax, 12
	mov	BYTE PTR vendor$[rsp+rax], 0

; 266  : 	au_get_boot_info()->auprint("CPU: Vendor -> %s \n", vendor);

	call	?au_get_boot_info@@YAPEAU_AURORA_INFO_@@XZ ; au_get_boot_info
	lea	rdx, QWORD PTR vendor$[rsp]
	lea	rcx, OFFSET FLAT:$SG3099
	call	QWORD PTR [rax+90]

; 267  : 
; 268  : 	char bandstring[49];
; 269  : 	x64_cpuid(0x80000002, &a, &b, &c, &d);

	mov	QWORD PTR [rsp+40], 0
	lea	rax, QWORD PTR d$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR c$[rsp]
	lea	r8, QWORD PTR b$[rsp]
	lea	rdx, QWORD PTR a$[rsp]
	mov	ecx, -2147483646			; 80000002H
	call	x64_cpuid

; 270  : 	*(uint32_t*)&bandstring[0] = a;

	mov	eax, 1
	imul	rax, rax, 0
	mov	ecx, DWORD PTR a$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 271  : 	*(uint32_t*)&bandstring[4] = b;

	mov	eax, 1
	imul	rax, rax, 4
	mov	ecx, DWORD PTR b$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 272  : 	*(uint32_t*)&bandstring[8] = c;

	mov	eax, 1
	imul	rax, rax, 8
	mov	ecx, DWORD PTR c$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 273  : 	*(uint32_t*)&bandstring[12] = d;

	mov	eax, 1
	imul	rax, rax, 12
	mov	ecx, DWORD PTR d$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 274  : 	x64_cpuid(0x80000003, &a, &b, &c, &d);

	mov	QWORD PTR [rsp+40], 0
	lea	rax, QWORD PTR d$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR c$[rsp]
	lea	r8, QWORD PTR b$[rsp]
	lea	rdx, QWORD PTR a$[rsp]
	mov	ecx, -2147483645			; 80000003H
	call	x64_cpuid

; 275  : 	*(uint32_t*)&bandstring[16] = a;

	mov	eax, 1
	imul	rax, rax, 16
	mov	ecx, DWORD PTR a$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 276  : 	*(uint32_t*)&bandstring[20] = b;

	mov	eax, 1
	imul	rax, rax, 20
	mov	ecx, DWORD PTR b$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 277  : 	*(uint32_t*)&bandstring[24] = c;

	mov	eax, 1
	imul	rax, rax, 24
	mov	ecx, DWORD PTR c$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 278  : 	*(uint32_t*)&bandstring[28] = d;

	mov	eax, 1
	imul	rax, rax, 28
	mov	ecx, DWORD PTR d$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 279  : 	x64_cpuid(0x80000004, &a, &b, &c, &d);

	mov	QWORD PTR [rsp+40], 0
	lea	rax, QWORD PTR d$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR c$[rsp]
	lea	r8, QWORD PTR b$[rsp]
	lea	rdx, QWORD PTR a$[rsp]
	mov	ecx, -2147483644			; 80000004H
	call	x64_cpuid

; 280  : 	*(uint32_t*)&bandstring[32] = a;

	mov	eax, 1
	imul	rax, rax, 32				; 00000020H
	mov	ecx, DWORD PTR a$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 281  : 	*(uint32_t*)&bandstring[36] = b;

	mov	eax, 1
	imul	rax, rax, 36				; 00000024H
	mov	ecx, DWORD PTR b$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 282  : 	*(uint32_t*)&bandstring[40] = c;

	mov	eax, 1
	imul	rax, rax, 40				; 00000028H
	mov	ecx, DWORD PTR c$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 283  : 	*(uint32_t*)&bandstring[44] = d;

	mov	eax, 1
	imul	rax, rax, 44				; 0000002cH
	mov	ecx, DWORD PTR d$[rsp]
	mov	DWORD PTR bandstring$[rsp+rax], ecx

; 284  : 	bandstring[48] = 0;

	mov	eax, 1
	imul	rax, rax, 48				; 00000030H
	mov	BYTE PTR bandstring$[rsp+rax], 0

; 285  : 	au_get_boot_info()->auprint("CPU: Brand = %s \n", bandstring);

	call	?au_get_boot_info@@YAPEAU_AURORA_INFO_@@XZ ; au_get_boot_info
	lea	rdx, QWORD PTR bandstring$[rsp]
	lea	rcx, OFFSET FLAT:$SG3113
	call	QWORD PTR [rax+90]

; 286  : }

	add	rsp, 168				; 000000a8H
	ret	0
x86_64_cpu_print_brand ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_cpu.cpp
_TEXT	SEGMENT
efer$ = 32
new_gdtr$1 = 40
new_gdt$2 = 48
bsp$ = 80
?x86_64_cpu_initialize@@YAX_N@Z PROC			; x86_64_cpu_initialize

; 296  : void x86_64_cpu_initialize(bool bsp) {

$LN4:
	mov	BYTE PTR [rsp+8], cl
	sub	rsp, 72					; 00000048H

; 297  : 	
; 298  : 	x86_64_gdt_initialize();

	call	?x86_64_gdt_initialize@@YAXXZ		; x86_64_gdt_initialize

; 299  : 	x86_64_idt_initialize();

	call	?x86_64_idt_initialize@@YAXXZ		; x86_64_idt_initialize

; 300  : 	x86_64_exception_init();

	call	?x86_64_exception_init@@YAXXZ		; x86_64_exception_init

; 301  : 	/* setup BSP cpu data */
; 302  : 	x86_64_cpu_feature_enable();

	call	?x86_64_cpu_feature_enable@@YAXXZ	; x86_64_cpu_feature_enable

; 303  : 
; 304  : 	/* Enable SYSCALL extension */
; 305  : 	size_t efer = x64_read_msr(IA32_EFER);

	mov	ecx, -1073741696			; c0000080H
	call	x64_read_msr
	mov	QWORD PTR efer$[rsp], rax

; 306  : 	efer |= (1 << 11);

	mov	rax, QWORD PTR efer$[rsp]
	bts	rax, 11
	mov	QWORD PTR efer$[rsp], rax

; 307  : 	efer |= 1;

	mov	rax, QWORD PTR efer$[rsp]
	or	rax, 1
	mov	QWORD PTR efer$[rsp], rax

; 308  : 	efer |= (1 << 0);

	mov	rax, QWORD PTR efer$[rsp]
	or	rax, 1
	mov	QWORD PTR efer$[rsp], rax

; 309  : 	efer |= 1;

	mov	rax, QWORD PTR efer$[rsp]
	or	rax, 1
	mov	QWORD PTR efer$[rsp], rax

; 310  : 	x64_write_msr(IA32_EFER, efer);

	mov	rdx, QWORD PTR efer$[rsp]
	mov	ecx, -1073741696			; c0000080H
	call	x64_write_msr

; 311  : 
; 312  : 	
; 313  : 	/* setup BSP cpu data */
; 314  : 	if (!bsp) {

	movzx	eax, BYTE PTR bsp$[rsp]
	test	eax, eax
	jne	SHORT $LN1@x86_64_cpu

; 315  : 		gdtr *new_gdtr = (gdtr*)x86_64_phys_to_virt((uint64_t)x86_64_pmmngr_alloc());

	call	x86_64_pmmngr_alloc
	mov	rcx, rax
	call	x86_64_phys_to_virt
	mov	QWORD PTR new_gdtr$1[rsp], rax

; 316  : 		memset(new_gdtr, 0, 4096);

	mov	r8d, 4096				; 00001000H
	xor	edx, edx
	mov	rcx, QWORD PTR new_gdtr$1[rsp]
	call	?memset@@YAXPEAXEI@Z			; memset

; 317  : 		gdt_entry* new_gdt = (gdt_entry*)x86_64_phys_to_virt((uint64_t)x86_64_pmmngr_alloc());

	call	x86_64_pmmngr_alloc
	mov	rcx, rax
	call	x86_64_phys_to_virt
	mov	QWORD PTR new_gdt$2[rsp], rax

; 318  : 		memset(new_gdtr, 0, 4096);

	mov	r8d, 4096				; 00001000H
	xor	edx, edx
	mov	rcx, QWORD PTR new_gdtr$1[rsp]
	call	?memset@@YAXPEAXEI@Z			; memset

; 319  : 		fill_gdt(new_gdt);

	mov	rcx, QWORD PTR new_gdt$2[rsp]
	call	?fill_gdt@@YAXPEAU_gdt@@@Z		; fill_gdt

; 320  : 		new_gdtr->gdtaddr = new_gdt;

	mov	rax, QWORD PTR new_gdtr$1[rsp]
	mov	rcx, QWORD PTR new_gdt$2[rsp]
	mov	QWORD PTR [rax+2], rcx

; 321  : 		new_gdtr->size = GDT_ENTRIES* sizeof(gdt_entry)-1;

	mov	eax, 71					; 00000047H
	mov	rcx, QWORD PTR new_gdtr$1[rsp]
	mov	WORD PTR [rcx], ax

; 322  : 		x64_lgdt(new_gdtr);

	mov	rcx, QWORD PTR new_gdtr$1[rsp]
	call	x64_lgdt
$LN1@x86_64_cpu:

; 323  : 	}
; 324  : }

	add	rsp, 72					; 00000048H
	ret	0
?x86_64_cpu_initialize@@YAX_N@Z ENDP			; x86_64_cpu_initialize
_TEXT	ENDS
END
