; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?queue_lock@@3PEAU_au_spinlock_@@EA		; queue_lock
PUBLIC	?sched_start_lock@@3PEAU_au_spinlock_@@EA	; sched_start_lock
PUBLIC	?thread_list_head@@3PEAU_thread_@@EA		; thread_list_head
PUBLIC	?thread_list_last@@3PEAU_thread_@@EA		; thread_list_last
PUBLIC	?thread_current@@3PEAU_thread_@@EA		; thread_current
PUBLIC	?idle@@3PEAU_thread_@@EA			; idle
PUBLIC	?scheduler_lock@@3PEAU_au_spinlock_@@EA		; scheduler_lock
_BSS	SEGMENT
?queue_lock@@3PEAU_au_spinlock_@@EA DQ 01H DUP (?)	; queue_lock
?sched_start_lock@@3PEAU_au_spinlock_@@EA DQ 01H DUP (?) ; sched_start_lock
start_scheduler DB 01H DUP (?)
	ALIGN	8

idle_lock DQ	01H DUP (?)
?thread_list_head@@3PEAU_thread_@@EA DQ 01H DUP (?)	; thread_list_head
?thread_list_last@@3PEAU_thread_@@EA DQ 01H DUP (?)	; thread_list_last
?thread_current@@3PEAU_thread_@@EA DQ 01H DUP (?)	; thread_current
?idle@@3PEAU_thread_@@EA DQ 01H DUP (?)			; idle
?scheduler_lock@@3PEAU_au_spinlock_@@EA DQ 01H DUP (?)	; scheduler_lock
_BSS	ENDS
CONST	SEGMENT
$SG3133	DB	'Idle ', 0aH, 00H
	ORG $+1
$SG3140	DB	'Idle thread rsp -> %x ', 0aH, 00H
$SG3149	DB	'Sched debug rcx -> %x ', 0aH, 00H
CONST	ENDS
PUBLIC	thread_insert
PUBLIC	thread_delete
PUBLIC	x86_64_create_kthread
PUBLIC	x86_64_create_uthread
PUBLIC	?x86_64_initialize_scheduler@@YAHXZ		; x86_64_initialize_scheduler
PUBLIC	?x86_64_sched_start@@YAXXZ			; x86_64_sched_start
PUBLIC	?x86_64_initialize_idle@@YAXXZ			; x86_64_initialize_idle
PUBLIC	?x86_64_get_idle_thr@@YAPEAU_thread_@@XZ	; x86_64_get_idle_thr
PUBLIC	?x86_64_sched_enable@@YAX_N@Z			; x86_64_sched_enable
PUBLIC	?x86_64_get_scheduler_lock@@YAPEAU_au_spinlock_@@XZ ; x86_64_get_scheduler_lock
PUBLIC	?x86_64_execute_idle@@YAXXZ			; x86_64_execute_idle
PUBLIC	?x86_64_get_current_thread@@YAPEAU_thread_@@XZ	; x86_64_get_current_thread
PUBLIC	?x86_64_next_thread@@YAXXZ			; x86_64_next_thread
PUBLIC	?x86_64_sceduler_isr@@YAX_KPEAX@Z		; x86_64_sceduler_isr
PUBLIC	?x86_64_idle_thread@@YAXXZ			; x86_64_idle_thread
PUBLIC	sched_debug
EXTRN	printf:PROC
EXTRN	?per_cpu_set_c_thread@@YAXPEAX@Z:PROC		; per_cpu_set_c_thread
EXTRN	x64_cli:PROC
EXTRN	x64_read_cr3:PROC
EXTRN	setvect:PROC
EXTRN	?x86_64_get_tss@@YAPEAU_tss@@XZ:PROC		; x86_64_get_tss
EXTRN	?apic_local_eoi@@YAXXZ:PROC			; apic_local_eoi
EXTRN	x86_64_phys_to_virt:PROC
EXTRN	x86_64_pmmngr_alloc:PROC
EXTRN	kmalloc:PROC
EXTRN	?memset@@YAXPEAXEI@Z:PROC			; memset
EXTRN	x86_64_save_context:PROC
EXTRN	x86_64_execute_context:PROC
pdata	SEGMENT
$pdata$x86_64_create_kthread DD imagerel $LN3
	DD	imagerel $LN3+519
	DD	imagerel $unwind$x86_64_create_kthread
$pdata$x86_64_create_uthread DD imagerel $LN3
	DD	imagerel $LN3+533
	DD	imagerel $unwind$x86_64_create_uthread
$pdata$?x86_64_initialize_scheduler@@YAHXZ DD imagerel $LN3
	DD	imagerel $LN3+107
	DD	imagerel $unwind$?x86_64_initialize_scheduler@@YAHXZ
$pdata$?x86_64_sched_start@@YAXXZ DD imagerel $LN3
	DD	imagerel $LN3+43
	DD	imagerel $unwind$?x86_64_sched_start@@YAXXZ
$pdata$?x86_64_initialize_idle@@YAXXZ DD imagerel $LN3
	DD	imagerel $LN3+21
	DD	imagerel $unwind$?x86_64_initialize_idle@@YAXXZ
$pdata$?x86_64_next_thread@@YAXXZ DD imagerel $LN7
	DD	imagerel $LN7+80
	DD	imagerel $unwind$?x86_64_next_thread@@YAXXZ
$pdata$?x86_64_sceduler_isr@@YAX_KPEAX@Z DD imagerel $LN6
	DD	imagerel $LN6+194
	DD	imagerel $unwind$?x86_64_sceduler_isr@@YAX_KPEAX@Z
$pdata$?x86_64_idle_thread@@YAXXZ DD imagerel $LN5
	DD	imagerel $LN5+30
	DD	imagerel $unwind$?x86_64_idle_thread@@YAXXZ
$pdata$sched_debug DD imagerel $LN3
	DD	imagerel $LN3+31
	DD	imagerel $unwind$sched_debug
pdata	ENDS
xdata	SEGMENT
$unwind$x86_64_create_kthread DD 011301H
	DD	06213H
$unwind$x86_64_create_uthread DD 011301H
	DD	06213H
$unwind$?x86_64_initialize_scheduler@@YAHXZ DD 010401H
	DD	06204H
$unwind$?x86_64_sched_start@@YAXXZ DD 010401H
	DD	04204H
$unwind$?x86_64_initialize_idle@@YAXXZ DD 010401H
	DD	04204H
$unwind$?x86_64_next_thread@@YAXXZ DD 010401H
	DD	02204H
$unwind$?x86_64_sceduler_isr@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?x86_64_idle_thread@@YAXXZ DD 010401H
	DD	04204H
$unwind$sched_debug DD 010901H
	DD	04209H
xdata	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
rcx$ = 48
sched_debug PROC

; 305  : extern "C" void sched_debug(void* rcx) {

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 306  : 	printf("Sched debug rcx -> %x \n", rcx);

	mov	rdx, QWORD PTR rcx$[rsp]
	lea	rcx, OFFSET FLAT:$SG3149
	call	printf

; 307  : }

	add	rsp, 40					; 00000028H
	ret	0
sched_debug ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
?x86_64_idle_thread@@YAXXZ PROC				; x86_64_idle_thread

; 265  : void x86_64_idle_thread() {	

$LN5:
	sub	rsp, 40					; 00000028H

; 266  : 	printf("Idle \n");

	lea	rcx, OFFSET FLAT:$SG3133
	call	printf
$LN2@x86_64_idl:

; 267  : 	while (1) {	

	xor	eax, eax
	cmp	eax, 1
	je	SHORT $LN1@x86_64_idl

; 268  : 		//x64_hlt();
; 269  : 	}

	jmp	SHORT $LN2@x86_64_idl
$LN1@x86_64_idl:

; 270  : }

	add	rsp, 40					; 00000028H
	ret	0
?x86_64_idle_thread@@YAXXZ ENDP				; x86_64_idle_thread
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?x86_64_sceduler_isr@@YAX_KPEAX@Z PROC			; x86_64_sceduler_isr

; 221  : void x86_64_sceduler_isr(size_t v, void* p) {

$LN6:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 222  : 	x64_cli();

	call	x64_cli

; 223  : 	//interrupt_stack_frame *frame = (interrupt_stack_frame*)p;
; 224  : #ifdef SMP
; 225  : 	thread_t * current_thr = (thread_t*)per_cpu_get_c_thread();
; 226  : #endif
; 227  : 	if (x86_64_save_context(thread_current) == 0) {

	mov	rcx, QWORD PTR ?thread_current@@3PEAU_thread_@@EA ; thread_current
	call	x86_64_save_context
	test	eax, eax
	jne	$LN3@x86_64_sce

; 228  : 		thread_current->cr3 = x64_read_cr3();

	call	x64_read_cr3
	mov	rcx, QWORD PTR ?thread_current@@3PEAU_thread_@@EA ; thread_current
	mov	QWORD PTR [rcx+192], rax

; 229  : 
; 230  : 		if (thread_current->privl == THREAD_PRIVL_USER)

	mov	rax, QWORD PTR ?thread_current@@3PEAU_thread_@@EA ; thread_current
	movzx	eax, BYTE PTR [rax+209]
	cmp	eax, 1
	jne	SHORT $LN2@x86_64_sce

; 231  : 			thread_current->kern_esp = x86_64_get_tss()->rsp[0];

	call	?x86_64_get_tss@@YAPEAU_tss@@XZ		; x86_64_get_tss
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR ?thread_current@@3PEAU_thread_@@EA ; thread_current
	mov	rax, QWORD PTR [rax+rcx+4]
	mov	QWORD PTR [rdx+200], rax
$LN2@x86_64_sce:

; 232  : 
; 233  : 		/*if (x86_64_fxsave_supported())
; 234  : 			x64_fxsave(thread_current->fxstate);*/
; 235  : 
; 236  : 
; 237  : 		apic_local_eoi();

	call	?apic_local_eoi@@YAXXZ			; apic_local_eoi

; 238  : 		x86_64_next_thread();

	call	?x86_64_next_thread@@YAXXZ		; x86_64_next_thread

; 239  : 		
; 240  : 
; 241  : 		/*if (x86_64_fxsave_supported())
; 242  : 			x64_fxrstor(thread_current->fxstate);*/
; 243  : 		if (thread_current->privl == THREAD_PRIVL_USER)

	mov	rax, QWORD PTR ?thread_current@@3PEAU_thread_@@EA ; thread_current
	movzx	eax, BYTE PTR [rax+209]
	cmp	eax, 1
	jne	SHORT $LN1@x86_64_sce

; 244  : 			x86_64_get_tss()->rsp[0] = thread_current->kern_esp;

	call	?x86_64_get_tss@@YAPEAU_tss@@XZ		; x86_64_get_tss
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR ?thread_current@@3PEAU_thread_@@EA ; thread_current
	mov	rdx, QWORD PTR [rdx+200]
	mov	QWORD PTR [rax+rcx+4], rdx
$LN1@x86_64_sce:

; 245  : 
; 246  : 		
; 247  : 		x86_64_execute_context(thread_current);

	mov	rcx, QWORD PTR ?thread_current@@3PEAU_thread_@@EA ; thread_current
	call	x86_64_execute_context
$LN3@x86_64_sce:
$end$7:

; 248  : 	}
; 249  : end:
; 250  : 	apic_local_eoi();

	call	?apic_local_eoi@@YAXXZ			; apic_local_eoi

; 251  : 	//au_free_spinlock(queue_lock);
; 252  : 	//x
; 253  : 	
; 254  : 	//
; 255  : }

	add	rsp, 40					; 00000028H
	ret	0
?x86_64_sceduler_isr@@YAX_KPEAX@Z ENDP			; x86_64_sceduler_isr
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
thr$ = 0
?x86_64_next_thread@@YAXXZ PROC				; x86_64_next_thread

; 196  : void x86_64_next_thread() {

$LN7:
	sub	rsp, 24

; 197  : 	//au_acquire_spinlock(scheduler_lock);
; 198  : 	thread_t *thr = thread_current;

	mov	rax, QWORD PTR ?thread_current@@3PEAU_thread_@@EA ; thread_current
	mov	QWORD PTR thr$[rsp], rax
$LN4@x86_64_nex:

; 199  : 	do {
; 200  : 		thr = thr->next;

	mov	rax, QWORD PTR thr$[rsp]
	mov	rax, QWORD PTR [rax+224]
	mov	QWORD PTR thr$[rsp], rax

; 201  : 		
; 202  : 		if (thr == NULL)

	cmp	QWORD PTR thr$[rsp], 0
	jne	SHORT $LN1@x86_64_nex

; 203  : 			thr = thread_list_head;

	mov	rax, QWORD PTR ?thread_list_head@@3PEAU_thread_@@EA ; thread_list_head
	mov	QWORD PTR thr$[rsp], rax
$LN1@x86_64_nex:

; 204  : 	} while (thr->state != THREAD_STATE_READY);

	mov	rax, QWORD PTR thr$[rsp]
	movzx	eax, BYTE PTR [rax+208]
	cmp	eax, 1
	jne	SHORT $LN4@x86_64_nex
$end$8:

; 205  : 
; 206  : end:
; 207  : 	thread_current = thr;

	mov	rax, QWORD PTR thr$[rsp]
	mov	QWORD PTR ?thread_current@@3PEAU_thread_@@EA, rax ; thread_current

; 208  : 	//au_free_spinlock(scheduler_lock);
; 209  : }

	add	rsp, 24
	ret	0
?x86_64_next_thread@@YAXXZ ENDP				; x86_64_next_thread
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
?x86_64_get_current_thread@@YAPEAU_thread_@@XZ PROC	; x86_64_get_current_thread

; 328  : 	return thread_current;

	mov	rax, QWORD PTR ?thread_current@@3PEAU_thread_@@EA ; thread_current

; 329  : }

	ret	0
?x86_64_get_current_thread@@YAPEAU_thread_@@XZ ENDP	; x86_64_get_current_thread
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
?x86_64_execute_idle@@YAXXZ PROC			; x86_64_execute_idle

; 313  : }

	ret	0
?x86_64_execute_idle@@YAXXZ ENDP			; x86_64_execute_idle
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
?x86_64_get_scheduler_lock@@YAPEAU_au_spinlock_@@XZ PROC ; x86_64_get_scheduler_lock

; 324  : 	return scheduler_lock;

	mov	rax, QWORD PTR ?scheduler_lock@@3PEAU_au_spinlock_@@EA ; scheduler_lock

; 325  : }

	ret	0
?x86_64_get_scheduler_lock@@YAPEAU_au_spinlock_@@XZ ENDP ; x86_64_get_scheduler_lock
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
value$ = 8
?x86_64_sched_enable@@YAX_N@Z PROC			; x86_64_sched_enable

; 319  : void x86_64_sched_enable(bool value) {

	mov	BYTE PTR [rsp+8], cl

; 320  : 	start_scheduler = true;

	mov	BYTE PTR start_scheduler, 1

; 321  : }

	ret	0
?x86_64_sched_enable@@YAX_N@Z ENDP			; x86_64_sched_enable
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
?x86_64_get_idle_thr@@YAPEAU_thread_@@XZ PROC		; x86_64_get_idle_thr

; 316  : 	return idle;

	mov	rax, QWORD PTR ?idle@@3PEAU_thread_@@EA	; idle

; 317  : }

	ret	0
?x86_64_get_idle_thr@@YAPEAU_thread_@@XZ ENDP		; x86_64_get_idle_thr
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
?x86_64_initialize_idle@@YAXXZ PROC			; x86_64_initialize_idle

; 292  : void x86_64_initialize_idle() {

$LN3:
	sub	rsp, 40					; 00000028H

; 293  : 	per_cpu_set_c_thread((void*)idle);

	mov	rcx, QWORD PTR ?idle@@3PEAU_thread_@@EA	; idle
	call	?per_cpu_set_c_thread@@YAXPEAX@Z	; per_cpu_set_c_thread

; 294  : }

	add	rsp, 40					; 00000028H
	ret	0
?x86_64_initialize_idle@@YAXXZ ENDP			; x86_64_initialize_idle
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
?x86_64_sched_start@@YAXXZ PROC				; x86_64_sched_start

; 299  : void x86_64_sched_start() {

$LN3:
	sub	rsp, 40					; 00000028H

; 300  : 	x64_cli();

	call	x64_cli

; 301  : 	setvect(0x40, x86_64_sceduler_isr);

	lea	rdx, OFFSET FLAT:?x86_64_sceduler_isr@@YAX_KPEAX@Z ; x86_64_sceduler_isr
	mov	ecx, 64					; 00000040H
	call	setvect

; 302  : 	x86_64_execute_context(idle);

	mov	rcx, QWORD PTR ?idle@@3PEAU_thread_@@EA	; idle
	call	x86_64_execute_context

; 303  : }

	add	rsp, 40					; 00000028H
	ret	0
?x86_64_sched_start@@YAXXZ ENDP				; x86_64_sched_start
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
tv65 = 32
?x86_64_initialize_scheduler@@YAHXZ PROC		; x86_64_initialize_scheduler

; 276  : int x86_64_initialize_scheduler() {

$LN3:
	sub	rsp, 56					; 00000038H

; 277  : 	idle = x86_64_create_kthread(x86_64_idle_thread, (x86_64_phys_to_virt((size_t)x86_64_pmmngr_alloc()) + 4096),
; 278  : 		x64_read_cr3());

	call	x64_read_cr3
	mov	QWORD PTR tv65[rsp], rax
	call	x86_64_pmmngr_alloc
	mov	rcx, rax
	call	x86_64_phys_to_virt
	add	rax, 4096				; 00001000H
	mov	rcx, QWORD PTR tv65[rsp]
	mov	r8, rcx
	mov	rdx, rax
	lea	rcx, OFFSET FLAT:?x86_64_idle_thread@@YAXXZ ; x86_64_idle_thread
	call	x86_64_create_kthread
	mov	QWORD PTR ?idle@@3PEAU_thread_@@EA, rax	; idle

; 279  : 	printf ("Idle thread rsp -> %x \n", idle->rsp);

	mov	rax, QWORD PTR ?idle@@3PEAU_thread_@@EA	; idle
	mov	rdx, QWORD PTR [rax+8]
	lea	rcx, OFFSET FLAT:$SG3140
	call	printf

; 280  : #ifdef SMP
; 281  : 	scheduler_lock = au_create_spinlock();
; 282  : 	queue_lock = au_create_spinlock();
; 283  : 	per_cpu_set_c_thread((void*)idle);
; 284  : #endif
; 285  : 	thread_current = idle;

	mov	rax, QWORD PTR ?idle@@3PEAU_thread_@@EA	; idle
	mov	QWORD PTR ?thread_current@@3PEAU_thread_@@EA, rax ; thread_current

; 286  : 	return 0;

	xor	eax, eax

; 287  : }

	add	rsp, 56					; 00000038H
	ret	0
?x86_64_initialize_scheduler@@YAHXZ ENDP		; x86_64_initialize_scheduler
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
thread$ = 32
entry$ = 64
stack$ = 72
cr3$ = 80
x86_64_create_uthread PROC

; 151  : thread_t * x86_64_create_uthread(void(*entry)(void), uint64_t stack, uint64_t cr3) {

$LN3:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 152  : 
; 153  : 	thread_t *thread = (thread_t*)kmalloc(sizeof(thread_t));

	mov	ecx, 240				; 000000f0H
	call	kmalloc
	mov	QWORD PTR thread$[rsp], rax

; 154  : 	memset(thread, 0, sizeof(thread_t));

	mov	r8d, 240				; 000000f0H
	xor	edx, edx
	mov	rcx, QWORD PTR thread$[rsp]
	call	?memset@@YAXPEAXEI@Z			; memset

; 155  : 	thread->ss = SEGVAL(GDT_ENTRY_USER_DATA, 3);

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax], 35			; 00000023H

; 156  : 	thread->rsp = (uint64_t)stack;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR stack$[rsp]
	mov	QWORD PTR [rax+8], rcx

; 157  : 	thread->rflags = 0x286;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+16], 646			; 00000286H

; 158  : 	thread->cs = SEGVAL(GDT_ENTRY_USER_CODE, 3);

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+24], 43			; 0000002bH

; 159  : 	thread->rip = (uint64_t)entry;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR entry$[rsp]
	mov	QWORD PTR [rax+32], rcx

; 160  : 	thread->rax = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+40], 0

; 161  : 	thread->rbx = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+48], 0

; 162  : 	thread->rcx = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+56], 0

; 163  : 	thread->rdx = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+64], 0

; 164  : 	thread->rsi = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+72], 0

; 165  : 	thread->rdi = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+80], 0

; 166  : 	thread->rbp = (uint64_t)thread->rsp;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	QWORD PTR [rax+88], rcx

; 167  : 	thread->r8 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+96], 0

; 168  : 	thread->r9 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+104], 0

; 169  : 	thread->r10 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+112], 0

; 170  : 	thread->r11 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+120], 0

; 171  : 	thread->r12 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+128], 0

; 172  : 	thread->r13 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+136], 0

; 173  : 	thread->r14 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+144], 0

; 174  : 	thread->r15 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+152], 0

; 175  : 	thread->ds = SEGVAL(GDT_ENTRY_USER_DATA, 3);

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+160], 35			; 00000023H

; 176  : 	thread->es = SEGVAL(GDT_ENTRY_USER_DATA, 3);

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+168], 35			; 00000023H

; 177  : 	thread->fs = SEGVAL(GDT_ENTRY_USER_DATA, 3);

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+176], 35			; 00000023H

; 178  : 	thread->gs = SEGVAL(GDT_ENTRY_USER_DATA, 3);

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+184], 35			; 00000023H

; 179  : 	thread->cr3 = cr3;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR cr3$[rsp]
	mov	QWORD PTR [rax+192], rcx

; 180  : 	thread->kern_esp = (x86_64_phys_to_virt((uint64_t)x86_64_pmmngr_alloc()) + 4096);

	call	x86_64_pmmngr_alloc
	mov	rcx, rax
	call	x86_64_phys_to_virt
	add	rax, 4096				; 00001000H
	mov	rcx, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rcx+200], rax

; 181  : 	thread->state = THREAD_STATE_READY;

	mov	rax, QWORD PTR thread$[rsp]
	mov	BYTE PTR [rax+208], 1

; 182  : 	thread->privl = THREAD_PRIVL_USER;

	mov	rax, QWORD PTR thread$[rsp]
	mov	BYTE PTR [rax+209], 1

; 183  : 	//thread->cpu_affinity = THREAD_CPU_AFFINITY_ANY;
; 184  : 	thread->fxstate = kmalloc(512);

	mov	ecx, 512				; 00000200H
	call	kmalloc
	mov	rcx, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rcx+216], rax

; 185  : 	memset(thread->fxstate, 0, 512);

	mov	r8d, 512				; 00000200H
	xor	edx, edx
	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR [rax+216]
	call	?memset@@YAXPEAXEI@Z			; memset

; 186  : 	thread_insert(thread);

	mov	rcx, QWORD PTR thread$[rsp]
	call	thread_insert

; 187  : 	return thread;

	mov	rax, QWORD PTR thread$[rsp]

; 188  : }

	add	rsp, 56					; 00000038H
	ret	0
x86_64_create_uthread ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
thread$ = 32
entry$ = 64
stack$ = 72
cr3$ = 80
x86_64_create_kthread PROC

; 105  : thread_t * x86_64_create_kthread(void(*entry)(void), uint64_t stack, uint64_t cr3) {

$LN3:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 106  : 	
; 107  : 	thread_t *thread = (thread_t*)kmalloc(sizeof(thread_t));

	mov	ecx, 240				; 000000f0H
	call	kmalloc
	mov	QWORD PTR thread$[rsp], rax

; 108  : 	memset(thread, 0, sizeof(thread_t));

	mov	r8d, 240				; 000000f0H
	xor	edx, edx
	mov	rcx, QWORD PTR thread$[rsp]
	call	?memset@@YAXPEAXEI@Z			; memset

; 109  : 	thread->ss = 0x10;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax], 16

; 110  : 	thread->rsp = (uint64_t)stack;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR stack$[rsp]
	mov	QWORD PTR [rax+8], rcx

; 111  : 	thread->rflags = 0x202;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+16], 514			; 00000202H

; 112  : 	thread->cs = 0x08;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+24], 8

; 113  : 	thread->rip = (uint64_t)entry;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR entry$[rsp]
	mov	QWORD PTR [rax+32], rcx

; 114  : 	thread->rax = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+40], 0

; 115  : 	thread->rbx = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+48], 0

; 116  : 	thread->rcx = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+56], 0

; 117  : 	thread->rdx = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+64], 0

; 118  : 	thread->rsi = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+72], 0

; 119  : 	thread->rdi = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+80], 0

; 120  : 	thread->rbp = (uint64_t)thread->rsp;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	QWORD PTR [rax+88], rcx

; 121  : 	thread->r8 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+96], 0

; 122  : 	thread->r9 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+104], 0

; 123  : 	thread->r10 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+112], 0

; 124  : 	thread->r11 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+120], 0

; 125  : 	thread->r12 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+128], 0

; 126  : 	thread->r13 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+136], 0

; 127  : 	thread->r14 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+144], 0

; 128  : 	thread->r15 = 0;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+152], 0

; 129  : 	thread->ds = 0x10;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+160], 16

; 130  : 	thread->es = 0x10;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+168], 16

; 131  : 	thread->fs = 0x10;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+176], 16

; 132  : 	thread->gs = 0x10;

	mov	rax, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rax+184], 16

; 133  : 	thread->cr3 = cr3;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR cr3$[rsp]
	mov	QWORD PTR [rax+192], rcx

; 134  : 	thread->kern_esp = stack;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR stack$[rsp]
	mov	QWORD PTR [rax+200], rcx

; 135  : 	thread->state = THREAD_STATE_READY;

	mov	rax, QWORD PTR thread$[rsp]
	mov	BYTE PTR [rax+208], 1

; 136  : 	thread->privl = THREAD_PRIVL_KERNEL;

	mov	rax, QWORD PTR thread$[rsp]
	mov	BYTE PTR [rax+209], 2

; 137  : 	//thread->cpu_affinity = THREAD_CPU_AFFINITY_ANY;
; 138  : 	thread->fxstate = kmalloc(512);

	mov	ecx, 512				; 00000200H
	call	kmalloc
	mov	rcx, QWORD PTR thread$[rsp]
	mov	QWORD PTR [rcx+216], rax

; 139  : 	memset(thread->fxstate, 0, 512);

	mov	r8d, 512				; 00000200H
	xor	edx, edx
	mov	rax, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR [rax+216]
	call	?memset@@YAXPEAXEI@Z			; memset

; 140  : 	thread_insert(thread);

	mov	rcx, QWORD PTR thread$[rsp]
	call	thread_insert

; 141  : 	return thread;

	mov	rax, QWORD PTR thread$[rsp]

; 142  : }

	add	rsp, 56					; 00000038H
	ret	0
x86_64_create_kthread ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
thread$ = 8
thread_delete PROC

; 80   : void thread_delete(thread_t * thread) {

	mov	QWORD PTR [rsp+8], rcx

; 81   : 	if (thread_list_head == NULL)

	cmp	QWORD PTR ?thread_list_head@@3PEAU_thread_@@EA, 0 ; thread_list_head
	jne	SHORT $LN5@thread_del

; 82   : 		return;

	jmp	$LN6@thread_del
$LN5@thread_del:

; 83   : 
; 84   : 	if (thread == thread_list_head) {

	mov	rax, QWORD PTR ?thread_list_head@@3PEAU_thread_@@EA ; thread_list_head
	cmp	QWORD PTR thread$[rsp], rax
	jne	SHORT $LN4@thread_del

; 85   : 		thread_list_head = thread_list_head->next;

	mov	rax, QWORD PTR ?thread_list_head@@3PEAU_thread_@@EA ; thread_list_head
	mov	rax, QWORD PTR [rax+224]
	mov	QWORD PTR ?thread_list_head@@3PEAU_thread_@@EA, rax ; thread_list_head

; 86   : 	}
; 87   : 	else {

	jmp	SHORT $LN3@thread_del
$LN4@thread_del:

; 88   : 		thread->prev->next = thread->next;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rax, QWORD PTR [rax+232]
	mov	rcx, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR [rcx+224]
	mov	QWORD PTR [rax+224], rcx
$LN3@thread_del:

; 89   : 	}
; 90   : 
; 91   : 	if (thread == thread_list_last) {

	mov	rax, QWORD PTR ?thread_list_last@@3PEAU_thread_@@EA ; thread_list_last
	cmp	QWORD PTR thread$[rsp], rax
	jne	SHORT $LN2@thread_del

; 92   : 		thread_list_last = thread->prev;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rax, QWORD PTR [rax+232]
	mov	QWORD PTR ?thread_list_last@@3PEAU_thread_@@EA, rax ; thread_list_last

; 93   : 	}
; 94   : 	else {

	jmp	SHORT $LN1@thread_del
$LN2@thread_del:

; 95   : 		thread->next->prev = thread->prev;

	mov	rax, QWORD PTR thread$[rsp]
	mov	rax, QWORD PTR [rax+224]
	mov	rcx, QWORD PTR thread$[rsp]
	mov	rcx, QWORD PTR [rcx+232]
	mov	QWORD PTR [rax+232], rcx
$LN1@thread_del:
$LN6@thread_del:

; 96   : 	}
; 97   : }

	ret	0
thread_delete ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_scheduler.cpp
_TEXT	SEGMENT
new_thread$ = 8
thread_insert PROC

; 58   : void thread_insert(thread_t * new_thread) {

	mov	QWORD PTR [rsp+8], rcx

; 59   : 	new_thread->next = NULL;

	mov	rax, QWORD PTR new_thread$[rsp]
	mov	QWORD PTR [rax+224], 0

; 60   : 	new_thread->prev = NULL;

	mov	rax, QWORD PTR new_thread$[rsp]
	mov	QWORD PTR [rax+232], 0

; 61   : 
; 62   : 	if (thread_list_head == NULL) {

	cmp	QWORD PTR ?thread_list_head@@3PEAU_thread_@@EA, 0 ; thread_list_head
	jne	SHORT $LN2@thread_ins

; 63   : 		thread_list_last = new_thread;

	mov	rax, QWORD PTR new_thread$[rsp]
	mov	QWORD PTR ?thread_list_last@@3PEAU_thread_@@EA, rax ; thread_list_last

; 64   : 		thread_list_head = new_thread;

	mov	rax, QWORD PTR new_thread$[rsp]
	mov	QWORD PTR ?thread_list_head@@3PEAU_thread_@@EA, rax ; thread_list_head

; 65   : 		thread_current = thread_list_last;

	mov	rax, QWORD PTR ?thread_list_last@@3PEAU_thread_@@EA ; thread_list_last
	mov	QWORD PTR ?thread_current@@3PEAU_thread_@@EA, rax ; thread_current

; 66   : 	}
; 67   : 	else {

	jmp	SHORT $LN1@thread_ins
$LN2@thread_ins:

; 68   : 		thread_list_last->next = new_thread;

	mov	rax, QWORD PTR ?thread_list_last@@3PEAU_thread_@@EA ; thread_list_last
	mov	rcx, QWORD PTR new_thread$[rsp]
	mov	QWORD PTR [rax+224], rcx

; 69   : 		new_thread->prev = thread_list_last;

	mov	rax, QWORD PTR new_thread$[rsp]
	mov	rcx, QWORD PTR ?thread_list_last@@3PEAU_thread_@@EA ; thread_list_last
	mov	QWORD PTR [rax+232], rcx
$LN1@thread_ins:

; 70   : 	}
; 71   : 
; 72   : 	thread_list_last = new_thread;

	mov	rax, QWORD PTR new_thread$[rsp]
	mov	QWORD PTR ?thread_list_last@@3PEAU_thread_@@EA, rax ; thread_list_last

; 73   : }

	ret	0
thread_insert ENDP
_TEXT	ENDS
END
