; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_BSS	SEGMENT
exception_lock DQ 01H DUP (?)
_BSS	ENDS
CONST	SEGMENT
$SG2858	DB	'***ARCH x86_64 : Exception Occured ***', 0aH, 00H
$SG2860	DB	'[aurora]: please inform it to the master of the kernel', 0aH
	DB	00H
$SG2859	DB	'[aurora]: We are sorry to say that, a processor invalid '
	DB	'exception has occured', 0aH, 00H
	ORG $+1
$SG2861	DB	'[aurora]: Below is the code of exception', 0aH, 00H
	ORG $+6
$SG2868	DB	0aH, 'Divide by 0', 00H
	ORG $+3
$SG2869	DB	'__PROCESSOR_DATA__', 0aH, 00H
	ORG $+4
$SG2870	DB	'RIP -> %x', 0aH, 00H
	ORG $+5
$SG2871	DB	'RSP -> %x', 0aH, 00H
	ORG $+5
$SG2872	DB	'RFLAGS -> %x', 0aH, 00H
	ORG $+2
$SG2882	DB	0aH, 'Single Step Trap', 00H
	ORG $+6
$SG2890	DB	0aH, 'NMI [Non-Muskable-Interrupt] Trap', 00H
	ORG $+5
$SG2898	DB	0aH, 'Breakpoint Trap', 00H
	ORG $+7
$SG2906	DB	0aH, 'Overflow Trap', 00H
	ORG $+1
$SG2914	DB	0aH, 'Bound Check Fault', 00H
	ORG $+5
$SG2924	DB	'Invalid Opcode Fault', 0aH, 00H
	ORG $+2
$SG2925	DB	'CPU ID -> %d ', 0aH, 00H
	ORG $+1
$SG2926	DB	'__PROCESSOR TRACE__', 0aH, 00H
	ORG $+3
$SG2927	DB	'RIP -> %x', 0aH, 00H
	ORG $+5
$SG2928	DB	'Stack -> %x', 0aH, 00H
	ORG $+3
$SG2929	DB	'RFLAGS -> %x', 0aH, 00H
	ORG $+2
$SG2930	DB	'CS -> %x', 0aH, 00H
	ORG $+6
$SG2931	DB	'SS -> %x', 0aH, 00H
	ORG $+6
$SG2939	DB	0aH, 'No Device Fault', 00H
	ORG $+7
$SG2947	DB	0aH, 'Double Fault Abort', 00H
	ORG $+4
$SG2955	DB	0aH, 'Invalid TSS Fault ', 00H
	ORG $+4
$SG2963	DB	0aH, 'No Segment Fault', 00H
	ORG $+6
$SG2971	DB	0aH, 'Stack Fault at ', 00H
	ORG $+7
$SG2981	DB	'Genral Protection Fault', 0aH, 00H
	ORG $+7
$SG2982	DB	'Current CPU id -> %d ', 0aH, 00H
	ORG $+1
$SG2983	DB	'Current thread -> %x ', 0aH, 00H
	ORG $+1
$SG2984	DB	'__PROCESSOR TRACE__', 0aH, 00H
	ORG $+3
$SG2985	DB	'RIP -> %x', 0aH, 00H
	ORG $+5
$SG2986	DB	'Stack -> %x', 0aH, 00H
	ORG $+3
$SG2987	DB	'RFLAGS -> %x', 0aH, 00H
	ORG $+2
$SG2988	DB	'CS -> %x, SS -> %x', 0aH, 00H
	ORG $+4
$SG3005	DB	'[aurora]: page fault ', 0aH, 00H
	ORG $+1
$SG3006	DB	'[aurora]: page fault at -> %x ', 0aH, 00H
$SG3007	DB	'[aurora]: current cpu -> %d ', 0aH, 00H
	ORG $+2
$SG3009	DB	'bit: present ', 0aH, 00H
	ORG $+1
$SG3012	DB	'bit: rw ', 0aH, 00H
	ORG $+6
$SG3015	DB	'bit: us ', 0aH, 00H
	ORG $+6
$SG3018	DB	'bit: resv ', 0aH, 00H
	ORG $+4
$SG3021	DB	'bit: id', 0aH, 00H
	ORG $+7
$SG3022	DB	'RIP -> %x ', 0aH, 00H
	ORG $+4
$SG3030	DB	0aH, 'FPU Fault', 00H
	ORG $+5
$SG3038	DB	0aH, 'Alignment Check Fault at address ', 00H
	ORG $+5
$SG3046	DB	0aH, 'Machine Check Abort', 00H
	ORG $+3
$SG3054	DB	0aH, 'SIMD FPU Fault', 00H
CONST	ENDS
PUBLIC	?x86_64_exception_init@@YAXXZ			; x86_64_exception_init
PUBLIC	?panic@@YAXPEBDZZ				; panic
PUBLIC	?divide_by_zero_fault@@YAX_KPEAX@Z		; divide_by_zero_fault
PUBLIC	?single_step_trap@@YAX_KPEAX@Z			; single_step_trap
PUBLIC	?nmi_trap@@YAX_KPEAX@Z				; nmi_trap
PUBLIC	?breakpoint_trap@@YAX_KPEAX@Z			; breakpoint_trap
PUBLIC	?overflow_trap@@YAX_KPEAX@Z			; overflow_trap
PUBLIC	?bounds_check_fault@@YAX_KPEAX@Z		; bounds_check_fault
PUBLIC	?invalid_opcode_fault@@YAX_KPEAX@Z		; invalid_opcode_fault
PUBLIC	?no_device_fault@@YAX_KPEAX@Z			; no_device_fault
PUBLIC	?double_fault_abort@@YAX_KPEAX@Z		; double_fault_abort
PUBLIC	?invalid_tss_fault@@YAX_KPEAX@Z			; invalid_tss_fault
PUBLIC	?no_segment_fault@@YAX_KPEAX@Z			; no_segment_fault
PUBLIC	?stack_fault@@YAX_KPEAX@Z			; stack_fault
PUBLIC	?general_protection_fault@@YAX_KPEAX@Z		; general_protection_fault
PUBLIC	?page_fault@@YAX_KPEAX@Z			; page_fault
PUBLIC	?fpu_fault@@YAX_KPEAX@Z				; fpu_fault
PUBLIC	?alignment_check_fault@@YAX_KPEAX@Z		; alignment_check_fault
PUBLIC	?machine_check_abort@@YAX_KPEAX@Z		; machine_check_abort
PUBLIC	?simd_fpu_fault@@YAX_KPEAX@Z			; simd_fpu_fault
EXTRN	printf:PROC
EXTRN	setvect:PROC
EXTRN	x64_cli:PROC
EXTRN	x64_read_cr2:PROC
EXTRN	x64_lock_acquire:PROC
EXTRN	?per_cpu_get_cpu_id@@YAEXZ:PROC			; per_cpu_get_cpu_id
EXTRN	?per_cpu_get_c_thread@@YAPEAXXZ:PROC		; per_cpu_get_c_thread
pdata	SEGMENT
$pdata$?x86_64_exception_init@@YAXXZ DD imagerel $LN3
	DD	imagerel $LN3+312
	DD	imagerel $unwind$?x86_64_exception_init@@YAXXZ
$pdata$?panic@@YAXPEBDZZ DD imagerel $LN3
	DD	imagerel $LN3+110
	DD	imagerel $unwind$?panic@@YAXPEBDZZ
$pdata$?divide_by_zero_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+146
	DD	imagerel $unwind$?divide_by_zero_fault@@YAX_KPEAX@Z
$pdata$?single_step_trap@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+71
	DD	imagerel $unwind$?single_step_trap@@YAX_KPEAX@Z
$pdata$?nmi_trap@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+61
	DD	imagerel $unwind$?nmi_trap@@YAX_KPEAX@Z
$pdata$?breakpoint_trap@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+61
	DD	imagerel $unwind$?breakpoint_trap@@YAX_KPEAX@Z
$pdata$?overflow_trap@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+61
	DD	imagerel $unwind$?overflow_trap@@YAX_KPEAX@Z
$pdata$?bounds_check_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+61
	DD	imagerel $unwind$?bounds_check_fault@@YAX_KPEAX@Z
$pdata$?invalid_opcode_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+210
	DD	imagerel $unwind$?invalid_opcode_fault@@YAX_KPEAX@Z
$pdata$?no_device_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+61
	DD	imagerel $unwind$?no_device_fault@@YAX_KPEAX@Z
$pdata$?double_fault_abort@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+38
	DD	imagerel $unwind$?double_fault_abort@@YAX_KPEAX@Z
$pdata$?invalid_tss_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+38
	DD	imagerel $unwind$?invalid_tss_fault@@YAX_KPEAX@Z
$pdata$?no_segment_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+38
	DD	imagerel $unwind$?no_segment_fault@@YAX_KPEAX@Z
$pdata$?stack_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+38
	DD	imagerel $unwind$?stack_fault@@YAX_KPEAX@Z
$pdata$?general_protection_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+218
	DD	imagerel $unwind$?general_protection_fault@@YAX_KPEAX@Z
$pdata$?page_fault@@YAX_KPEAX@Z DD imagerel $LN16
	DD	imagerel $LN16+356
	DD	imagerel $unwind$?page_fault@@YAX_KPEAX@Z
$pdata$?fpu_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+61
	DD	imagerel $unwind$?fpu_fault@@YAX_KPEAX@Z
$pdata$?alignment_check_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+38
	DD	imagerel $unwind$?alignment_check_fault@@YAX_KPEAX@Z
$pdata$?machine_check_abort@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+38
	DD	imagerel $unwind$?machine_check_abort@@YAX_KPEAX@Z
$pdata$?simd_fpu_fault@@YAX_KPEAX@Z DD imagerel $LN5
	DD	imagerel $LN5+38
	DD	imagerel $unwind$?simd_fpu_fault@@YAX_KPEAX@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?x86_64_exception_init@@YAXXZ DD 010401H
	DD	04204H
$unwind$?panic@@YAXPEBDZZ DD 011801H
	DD	04218H
$unwind$?divide_by_zero_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0620eH
$unwind$?single_step_trap@@YAX_KPEAX@Z DD 010e01H
	DD	0620eH
$unwind$?nmi_trap@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?breakpoint_trap@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?overflow_trap@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?bounds_check_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?invalid_opcode_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0620eH
$unwind$?no_device_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?double_fault_abort@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?invalid_tss_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?no_segment_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?stack_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?general_protection_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0620eH
$unwind$?page_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0a20eH
$unwind$?fpu_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?alignment_check_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?machine_check_abort@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
$unwind$?simd_fpu_fault@@YAX_KPEAX@Z DD 010e01H
	DD	0420eH
xdata	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?simd_fpu_fault@@YAX_KPEAX@Z PROC			; simd_fpu_fault

; 241  : void simd_fpu_fault(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 242  : 	x64_cli();

	call	x64_cli

; 243  : 	panic("\nSIMD FPU Fault");

	lea	rcx, OFFSET FLAT:$SG3054
	call	?panic@@YAXPEBDZZ			; panic
$LN2@simd_fpu_f:

; 244  : 	for (;;);

	jmp	SHORT $LN2@simd_fpu_f

; 245  : }

	add	rsp, 40					; 00000028H
	ret	0
?simd_fpu_fault@@YAX_KPEAX@Z ENDP			; simd_fpu_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?machine_check_abort@@YAX_KPEAX@Z PROC			; machine_check_abort

; 234  : void machine_check_abort(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 235  : 	x64_cli();

	call	x64_cli

; 236  : 	panic("\nMachine Check Abort");

	lea	rcx, OFFSET FLAT:$SG3046
	call	?panic@@YAXPEBDZZ			; panic
$LN2@machine_ch:

; 237  : 	for (;;);

	jmp	SHORT $LN2@machine_ch

; 238  : }

	add	rsp, 40					; 00000028H
	ret	0
?machine_check_abort@@YAX_KPEAX@Z ENDP			; machine_check_abort
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?alignment_check_fault@@YAX_KPEAX@Z PROC		; alignment_check_fault

; 227  : void alignment_check_fault(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 228  : 	x64_cli();

	call	x64_cli

; 229  : 	panic("\nAlignment Check Fault at address ");

	lea	rcx, OFFSET FLAT:$SG3038
	call	?panic@@YAXPEBDZZ			; panic
$LN2@alignment_:

; 230  : 	for (;;);

	jmp	SHORT $LN2@alignment_

; 231  : }

	add	rsp, 40					; 00000028H
	ret	0
?alignment_check_fault@@YAX_KPEAX@Z ENDP		; alignment_check_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
vector$ = 48
p$ = 56
?fpu_fault@@YAX_KPEAX@Z PROC				; fpu_fault

; 217  : void fpu_fault(size_t vector, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 218  : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 219  : 	x64_cli();

	call	x64_cli

; 220  : 	panic("\nFPU Fault");

	lea	rcx, OFFSET FLAT:$SG3030
	call	?panic@@YAXPEBDZZ			; panic

; 221  : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@fpu_fault:

; 222  : 	for (;;);

	jmp	SHORT $LN2@fpu_fault

; 223  : }

	add	rsp, 40					; 00000028H
	ret	0
?fpu_fault@@YAX_KPEAX@Z ENDP				; fpu_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
tv69 = 32
present$ = 36
rw$ = 40
us$ = 44
resv$ = 48
id$ = 52
frame$ = 56
vaddr$ = 64
vector$ = 96
param$ = 104
?page_fault@@YAX_KPEAX@Z PROC				; page_fault

; 181  : void page_fault(size_t vector, void* param){

$LN16:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H

; 182  : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 183  : 	x64_cli();

	call	x64_cli

; 184  : 
; 185  : 	interrupt_stack_frame *frame = (interrupt_stack_frame*)param;

	mov	rax, QWORD PTR param$[rsp]
	mov	QWORD PTR frame$[rsp], rax

; 186  : 	void* vaddr = (void*)x64_read_cr2();

	call	x64_read_cr2
	mov	QWORD PTR vaddr$[rsp], rax

; 187  : 
; 188  : 	int present = !(frame->error & 0x1);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rax, QWORD PTR [rax+8]
	and	rax, 1
	test	rax, rax
	jne	SHORT $LN14@page_fault
	mov	DWORD PTR tv69[rsp], 1
	jmp	SHORT $LN15@page_fault
$LN14@page_fault:
	mov	DWORD PTR tv69[rsp], 0
$LN15@page_fault:
	mov	eax, DWORD PTR tv69[rsp]
	mov	DWORD PTR present$[rsp], eax

; 189  : 	int rw = frame->error & 0x2;

	mov	rax, QWORD PTR frame$[rsp]
	mov	rax, QWORD PTR [rax+8]
	and	rax, 2
	mov	DWORD PTR rw$[rsp], eax

; 190  : 	int us = frame->error & 0x4;

	mov	rax, QWORD PTR frame$[rsp]
	mov	rax, QWORD PTR [rax+8]
	and	rax, 4
	mov	DWORD PTR us$[rsp], eax

; 191  : 	int resv = frame->error & 0x8;

	mov	rax, QWORD PTR frame$[rsp]
	mov	rax, QWORD PTR [rax+8]
	and	rax, 8
	mov	DWORD PTR resv$[rsp], eax

; 192  : 	int id = frame->error & 0x10;

	mov	rax, QWORD PTR frame$[rsp]
	mov	rax, QWORD PTR [rax+8]
	and	rax, 16
	mov	DWORD PTR id$[rsp], eax

; 193  : 
; 194  : 	panic("[aurora]: page fault \n");

	lea	rcx, OFFSET FLAT:$SG3005
	call	?panic@@YAXPEBDZZ			; panic

; 195  : 	printf("[aurora]: page fault at -> %x \n", vaddr);

	mov	rdx, QWORD PTR vaddr$[rsp]
	lea	rcx, OFFSET FLAT:$SG3006
	call	printf

; 196  : 	printf("[aurora]: current cpu -> %d \n", per_cpu_get_cpu_id());

	call	?per_cpu_get_cpu_id@@YAEXZ		; per_cpu_get_cpu_id
	movzx	eax, al
	mov	edx, eax
	lea	rcx, OFFSET FLAT:$SG3007
	call	printf

; 197  : 	if (present)

	cmp	DWORD PTR present$[rsp], 0
	je	SHORT $LN11@page_fault

; 198  : 		printf("bit: present \n");

	lea	rcx, OFFSET FLAT:$SG3009
	call	printf
	jmp	SHORT $LN10@page_fault
$LN11@page_fault:

; 199  : 	else if (rw)

	cmp	DWORD PTR rw$[rsp], 0
	je	SHORT $LN9@page_fault

; 200  : 		printf("bit: rw \n");

	lea	rcx, OFFSET FLAT:$SG3012
	call	printf
	jmp	SHORT $LN8@page_fault
$LN9@page_fault:

; 201  : 	else if (us)

	cmp	DWORD PTR us$[rsp], 0
	je	SHORT $LN7@page_fault

; 202  : 		printf("bit: us \n");

	lea	rcx, OFFSET FLAT:$SG3015
	call	printf
	jmp	SHORT $LN6@page_fault
$LN7@page_fault:

; 203  : 	else if (resv)

	cmp	DWORD PTR resv$[rsp], 0
	je	SHORT $LN5@page_fault

; 204  : 		printf("bit: resv \n");

	lea	rcx, OFFSET FLAT:$SG3018
	call	printf
	jmp	SHORT $LN4@page_fault
$LN5@page_fault:

; 205  : 	else if (id)

	cmp	DWORD PTR id$[rsp], 0
	je	SHORT $LN3@page_fault

; 206  : 		printf("bit: id\n");

	lea	rcx, OFFSET FLAT:$SG3021
	call	printf
$LN3@page_fault:
$LN4@page_fault:
$LN6@page_fault:
$LN8@page_fault:
$LN10@page_fault:

; 207  : 
; 208  : 	printf("RIP -> %x \n", frame->rip);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+16]
	lea	rcx, OFFSET FLAT:$SG3022
	call	printf

; 209  : 
; 210  : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@page_fault:

; 211  : 
; 212  : 	for (;;);

	jmp	SHORT $LN2@page_fault

; 213  : }

	add	rsp, 88					; 00000058H
	ret	0
?page_fault@@YAX_KPEAX@Z ENDP				; page_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
frame$ = 32
v$ = 64
p$ = 72
?general_protection_fault@@YAX_KPEAX@Z PROC		; general_protection_fault

; 162  : void general_protection_fault(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 163  : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 164  : 	x64_cli();

	call	x64_cli

; 165  : 	interrupt_stack_frame *frame = (interrupt_stack_frame*)p;

	mov	rax, QWORD PTR p$[rsp]
	mov	QWORD PTR frame$[rsp], rax

; 166  : 	panic ("Genral Protection Fault\n");

	lea	rcx, OFFSET FLAT:$SG2981
	call	?panic@@YAXPEBDZZ			; panic

; 167  : 	printf("Current CPU id -> %d \n", per_cpu_get_cpu_id());

	call	?per_cpu_get_cpu_id@@YAEXZ		; per_cpu_get_cpu_id
	movzx	eax, al
	mov	edx, eax
	lea	rcx, OFFSET FLAT:$SG2982
	call	printf

; 168  : 	printf("Current thread -> %x \n", per_cpu_get_c_thread());

	call	?per_cpu_get_c_thread@@YAPEAXXZ		; per_cpu_get_c_thread
	mov	rdx, rax
	lea	rcx, OFFSET FLAT:$SG2983
	call	printf

; 169  : 	printf ("__PROCESSOR TRACE__\n");

	lea	rcx, OFFSET FLAT:$SG2984
	call	printf

; 170  : 	printf ("RIP -> %x\n",frame->rip);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+16]
	lea	rcx, OFFSET FLAT:$SG2985
	call	printf

; 171  : 	printf ("Stack -> %x\n", frame->rsp);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+40]
	lea	rcx, OFFSET FLAT:$SG2986
	call	printf

; 172  : 	printf ("RFLAGS -> %x\n", frame->rflags);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+32]
	lea	rcx, OFFSET FLAT:$SG2987
	call	printf

; 173  : 	printf ("CS -> %x, SS -> %x\n", frame->cs, frame->ss);

	mov	rax, QWORD PTR frame$[rsp]
	mov	r8, QWORD PTR [rax+48]
	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+24]
	lea	rcx, OFFSET FLAT:$SG2988
	call	printf

; 174  : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@general_pr:

; 175  : 	for(;;);

	jmp	SHORT $LN2@general_pr

; 176  : }

	add	rsp, 56					; 00000038H
	ret	0
?general_protection_fault@@YAX_KPEAX@Z ENDP		; general_protection_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?stack_fault@@YAX_KPEAX@Z PROC				; stack_fault

; 154  : void stack_fault(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 155  : 	x64_cli();

	call	x64_cli

; 156  : 	panic("\nStack Fault at ");

	lea	rcx, OFFSET FLAT:$SG2971
	call	?panic@@YAXPEBDZZ			; panic
$LN2@stack_faul:

; 157  : 	for (;;);

	jmp	SHORT $LN2@stack_faul

; 158  : }

	add	rsp, 40					; 00000028H
	ret	0
?stack_fault@@YAX_KPEAX@Z ENDP				; stack_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?no_segment_fault@@YAX_KPEAX@Z PROC			; no_segment_fault

; 147  : void no_segment_fault(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 148  : 	x64_cli();

	call	x64_cli

; 149  : 	panic("\nNo Segment Fault");

	lea	rcx, OFFSET FLAT:$SG2963
	call	?panic@@YAXPEBDZZ			; panic
$LN2@no_segment:

; 150  : 	for (;;);

	jmp	SHORT $LN2@no_segment

; 151  : }

	add	rsp, 40					; 00000028H
	ret	0
?no_segment_fault@@YAX_KPEAX@Z ENDP			; no_segment_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?invalid_tss_fault@@YAX_KPEAX@Z PROC			; invalid_tss_fault

; 140  : void invalid_tss_fault(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 141  : 	x64_cli();

	call	x64_cli

; 142  : 	panic("\nInvalid TSS Fault ");

	lea	rcx, OFFSET FLAT:$SG2955
	call	?panic@@YAXPEBDZZ			; panic
$LN2@invalid_ts:

; 143  : 	for (;;);

	jmp	SHORT $LN2@invalid_ts

; 144  : }

	add	rsp, 40					; 00000028H
	ret	0
?invalid_tss_fault@@YAX_KPEAX@Z ENDP			; invalid_tss_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?double_fault_abort@@YAX_KPEAX@Z PROC			; double_fault_abort

; 133  : void double_fault_abort(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 134  : 	x64_cli();

	call	x64_cli

; 135  : 	panic("\nDouble Fault Abort");

	lea	rcx, OFFSET FLAT:$SG2947
	call	?panic@@YAXPEBDZZ			; panic
$LN2@double_fau:

; 136  : 	for (;;);

	jmp	SHORT $LN2@double_fau

; 137  : }

	add	rsp, 40					; 00000028H
	ret	0
?double_fault_abort@@YAX_KPEAX@Z ENDP			; double_fault_abort
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?no_device_fault@@YAX_KPEAX@Z PROC			; no_device_fault

; 124  : void no_device_fault(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 125  : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 126  : 	x64_cli();

	call	x64_cli

; 127  : 	panic("\nNo Device Fault");

	lea	rcx, OFFSET FLAT:$SG2939
	call	?panic@@YAXPEBDZZ			; panic

; 128  : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@no_device_:

; 129  : 	for (;;);

	jmp	SHORT $LN2@no_device_

; 130  : }

	add	rsp, 40					; 00000028H
	ret	0
?no_device_fault@@YAX_KPEAX@Z ENDP			; no_device_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
frame$ = 32
v$ = 64
p$ = 72
?invalid_opcode_fault@@YAX_KPEAX@Z PROC			; invalid_opcode_fault

; 107  : void invalid_opcode_fault(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 108  : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 109  : 	x64_cli();

	call	x64_cli

; 110  : 	interrupt_stack_frame *frame = (interrupt_stack_frame*)p;

	mov	rax, QWORD PTR p$[rsp]
	mov	QWORD PTR frame$[rsp], rax

; 111  : 	panic("Invalid Opcode Fault\n");

	lea	rcx, OFFSET FLAT:$SG2924
	call	?panic@@YAXPEBDZZ			; panic

; 112  : 	printf("CPU ID -> %d \n", per_cpu_get_cpu_id());

	call	?per_cpu_get_cpu_id@@YAEXZ		; per_cpu_get_cpu_id
	movzx	eax, al
	mov	edx, eax
	lea	rcx, OFFSET FLAT:$SG2925
	call	printf

; 113  : 	printf("__PROCESSOR TRACE__\n");

	lea	rcx, OFFSET FLAT:$SG2926
	call	printf

; 114  : 	printf("RIP -> %x\n", frame->rip);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+16]
	lea	rcx, OFFSET FLAT:$SG2927
	call	printf

; 115  : 	printf("Stack -> %x\n", frame->rsp);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+40]
	lea	rcx, OFFSET FLAT:$SG2928
	call	printf

; 116  : 	printf("RFLAGS -> %x\n", frame->rflags);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+32]
	lea	rcx, OFFSET FLAT:$SG2929
	call	printf

; 117  : 	printf("CS -> %x\n", frame->cs);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+24]
	lea	rcx, OFFSET FLAT:$SG2930
	call	printf

; 118  : 	printf("SS -> %x\n", frame->ss);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+48]
	lea	rcx, OFFSET FLAT:$SG2931
	call	printf

; 119  : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@invalid_op:

; 120  : 	for (;;);

	jmp	SHORT $LN2@invalid_op

; 121  : }

	add	rsp, 56					; 00000038H
	ret	0
?invalid_opcode_fault@@YAX_KPEAX@Z ENDP			; invalid_opcode_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?bounds_check_fault@@YAX_KPEAX@Z PROC			; bounds_check_fault

; 98   : void bounds_check_fault(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 99   : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 100  : 	x64_cli();

	call	x64_cli

; 101  : 	panic("\nBound Check Fault");

	lea	rcx, OFFSET FLAT:$SG2914
	call	?panic@@YAXPEBDZZ			; panic

; 102  : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@bounds_che:

; 103  : 	for (;;);

	jmp	SHORT $LN2@bounds_che

; 104  : }

	add	rsp, 40					; 00000028H
	ret	0
?bounds_check_fault@@YAX_KPEAX@Z ENDP			; bounds_check_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
v$ = 48
p$ = 56
?overflow_trap@@YAX_KPEAX@Z PROC			; overflow_trap

; 89   : void overflow_trap(size_t v, void* p){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 90   : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 91   : 	x64_cli();

	call	x64_cli

; 92   : 	panic("\nOverflow Trap");

	lea	rcx, OFFSET FLAT:$SG2906
	call	?panic@@YAXPEBDZZ			; panic

; 93   : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@overflow_t:

; 94   : 	for (;;);

	jmp	SHORT $LN2@overflow_t

; 95   : }

	add	rsp, 40					; 00000028H
	ret	0
?overflow_trap@@YAX_KPEAX@Z ENDP			; overflow_trap
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
vector$ = 48
param$ = 56
?breakpoint_trap@@YAX_KPEAX@Z PROC			; breakpoint_trap

; 80   : void breakpoint_trap(size_t vector, void* param){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 81   : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 82   : 	x64_cli();

	call	x64_cli

; 83   : 	panic("\nBreakpoint Trap");

	lea	rcx, OFFSET FLAT:$SG2898
	call	?panic@@YAXPEBDZZ			; panic

; 84   : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@breakpoint:

; 85   : 	for (;;);

	jmp	SHORT $LN2@breakpoint

; 86   : }

	add	rsp, 40					; 00000028H
	ret	0
?breakpoint_trap@@YAX_KPEAX@Z ENDP			; breakpoint_trap
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
vector$ = 48
param$ = 56
?nmi_trap@@YAX_KPEAX@Z PROC				; nmi_trap

; 70   : void nmi_trap(size_t vector, void* param){

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 71   : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 72   : 	x64_cli();

	call	x64_cli

; 73   : 	panic("\nNMI [Non-Muskable-Interrupt] Trap");

	lea	rcx, OFFSET FLAT:$SG2890
	call	?panic@@YAXPEBDZZ			; panic

; 74   : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@nmi_trap:

; 75   : 	for (;;);

	jmp	SHORT $LN2@nmi_trap

; 76   : 
; 77   : }

	add	rsp, 40					; 00000028H
	ret	0
?nmi_trap@@YAX_KPEAX@Z ENDP				; nmi_trap
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
frame$ = 32
vector$ = 64
param$ = 72
?single_step_trap@@YAX_KPEAX@Z PROC			; single_step_trap

; 61   : void single_step_trap(size_t vector, void* param) {

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 62   : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 63   : 	x64_cli();

	call	x64_cli

; 64   : 	interrupt_stack_frame *frame = (interrupt_stack_frame*)param;

	mov	rax, QWORD PTR param$[rsp]
	mov	QWORD PTR frame$[rsp], rax

; 65   : 	panic("\nSingle Step Trap");

	lea	rcx, OFFSET FLAT:$SG2882
	call	?panic@@YAXPEBDZZ			; panic

; 66   : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@single_ste:

; 67   : 	for (;;);

	jmp	SHORT $LN2@single_ste

; 68   : }

	add	rsp, 56					; 00000038H
	ret	0
?single_step_trap@@YAX_KPEAX@Z ENDP			; single_step_trap
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
frame$ = 32
vector$ = 64
param$ = 72
?divide_by_zero_fault@@YAX_KPEAX@Z PROC			; divide_by_zero_fault

; 47   : void divide_by_zero_fault(size_t vector, void* param) {

$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 48   : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 49   : 	x64_cli();

	call	x64_cli

; 50   : 	interrupt_stack_frame *frame = (interrupt_stack_frame*)param;

	mov	rax, QWORD PTR param$[rsp]
	mov	QWORD PTR frame$[rsp], rax

; 51   : 	panic("\nDivide by 0");

	lea	rcx, OFFSET FLAT:$SG2868
	call	?panic@@YAXPEBDZZ			; panic

; 52   : 
; 53   : 	printf("__PROCESSOR_DATA__\n");

	lea	rcx, OFFSET FLAT:$SG2869
	call	printf

; 54   : 	printf("RIP -> %x\n", frame->rip);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+16]
	lea	rcx, OFFSET FLAT:$SG2870
	call	printf

; 55   : 	printf("RSP -> %x\n", frame->rsp);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+40]
	lea	rcx, OFFSET FLAT:$SG2871
	call	printf

; 56   : 	printf("RFLAGS -> %x\n", frame->rflags);

	mov	rax, QWORD PTR frame$[rsp]
	mov	rdx, QWORD PTR [rax+32]
	lea	rcx, OFFSET FLAT:$SG2872
	call	printf

; 57   : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0
$LN2@divide_by_:

; 58   : 	for (;;);

	jmp	SHORT $LN2@divide_by_

; 59   : }

	add	rsp, 56					; 00000038H
	ret	0
?divide_by_zero_fault@@YAX_KPEAX@Z ENDP			; divide_by_zero_fault
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
msg$ = 48
?panic@@YAXPEBDZZ PROC					; panic

; 37   : void panic(const char* msg, ...) {

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	sub	rsp, 40					; 00000028H

; 38   : 	x64_lock_acquire(&exception_lock);

	lea	rcx, OFFSET FLAT:exception_lock
	call	x64_lock_acquire

; 39   : 	printf("***ARCH x86_64 : Exception Occured ***\n");

	lea	rcx, OFFSET FLAT:$SG2858
	call	printf

; 40   : 	printf("[aurora]: We are sorry to say that, a processor invalid exception has occured\n");

	lea	rcx, OFFSET FLAT:$SG2859
	call	printf

; 41   : 	printf("[aurora]: please inform it to the master of the kernel\n");

	lea	rcx, OFFSET FLAT:$SG2860
	call	printf

; 42   : 	printf("[aurora]: Below is the code of exception\n");

	lea	rcx, OFFSET FLAT:$SG2861
	call	printf

; 43   : 	exception_lock = 0;

	mov	QWORD PTR exception_lock, 0

; 44   : 	printf(msg);

	mov	rcx, QWORD PTR msg$[rsp]
	call	printf

; 45   : }

	add	rsp, 40					; 00000028H
	ret	0
?panic@@YAXPEBDZZ ENDP					; panic
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\aurora kernel\kernel\arch\x86_64\x86_64_exception.cpp
_TEXT	SEGMENT
?x86_64_exception_init@@YAXXZ PROC			; x86_64_exception_init

; 247  : void x86_64_exception_init() {

$LN3:
	sub	rsp, 40					; 00000028H

; 248  : 	setvect(0, divide_by_zero_fault);

	lea	rdx, OFFSET FLAT:?divide_by_zero_fault@@YAX_KPEAX@Z ; divide_by_zero_fault
	xor	ecx, ecx
	call	setvect

; 249  : 	setvect(1, single_step_trap);

	lea	rdx, OFFSET FLAT:?single_step_trap@@YAX_KPEAX@Z ; single_step_trap
	mov	ecx, 1
	call	setvect

; 250  : 	setvect(2, nmi_trap);

	lea	rdx, OFFSET FLAT:?nmi_trap@@YAX_KPEAX@Z	; nmi_trap
	mov	ecx, 2
	call	setvect

; 251  : 	setvect(3, breakpoint_trap);

	lea	rdx, OFFSET FLAT:?breakpoint_trap@@YAX_KPEAX@Z ; breakpoint_trap
	mov	ecx, 3
	call	setvect

; 252  : 	setvect(4, overflow_trap);

	lea	rdx, OFFSET FLAT:?overflow_trap@@YAX_KPEAX@Z ; overflow_trap
	mov	ecx, 4
	call	setvect

; 253  : 	setvect(5, bounds_check_fault);

	lea	rdx, OFFSET FLAT:?bounds_check_fault@@YAX_KPEAX@Z ; bounds_check_fault
	mov	ecx, 5
	call	setvect

; 254  : 	setvect(6, invalid_opcode_fault);

	lea	rdx, OFFSET FLAT:?invalid_opcode_fault@@YAX_KPEAX@Z ; invalid_opcode_fault
	mov	ecx, 6
	call	setvect

; 255  : 	setvect(7, no_device_fault);

	lea	rdx, OFFSET FLAT:?no_device_fault@@YAX_KPEAX@Z ; no_device_fault
	mov	ecx, 7
	call	setvect

; 256  : 	setvect(8, double_fault_abort);

	lea	rdx, OFFSET FLAT:?double_fault_abort@@YAX_KPEAX@Z ; double_fault_abort
	mov	ecx, 8
	call	setvect

; 257  : 	setvect(10, invalid_tss_fault);

	lea	rdx, OFFSET FLAT:?invalid_tss_fault@@YAX_KPEAX@Z ; invalid_tss_fault
	mov	ecx, 10
	call	setvect

; 258  : 	setvect(11, no_segment_fault);

	lea	rdx, OFFSET FLAT:?no_segment_fault@@YAX_KPEAX@Z ; no_segment_fault
	mov	ecx, 11
	call	setvect

; 259  : 	setvect(12, stack_fault);

	lea	rdx, OFFSET FLAT:?stack_fault@@YAX_KPEAX@Z ; stack_fault
	mov	ecx, 12
	call	setvect

; 260  : 	setvect(13, general_protection_fault);

	lea	rdx, OFFSET FLAT:?general_protection_fault@@YAX_KPEAX@Z ; general_protection_fault
	mov	ecx, 13
	call	setvect

; 261  : 	setvect(14, page_fault);

	lea	rdx, OFFSET FLAT:?page_fault@@YAX_KPEAX@Z ; page_fault
	mov	ecx, 14
	call	setvect

; 262  : 	setvect(16, fpu_fault);

	lea	rdx, OFFSET FLAT:?fpu_fault@@YAX_KPEAX@Z ; fpu_fault
	mov	ecx, 16
	call	setvect

; 263  : 	setvect(17, alignment_check_fault);

	lea	rdx, OFFSET FLAT:?alignment_check_fault@@YAX_KPEAX@Z ; alignment_check_fault
	mov	ecx, 17
	call	setvect

; 264  : 	setvect(18, machine_check_abort);

	lea	rdx, OFFSET FLAT:?machine_check_abort@@YAX_KPEAX@Z ; machine_check_abort
	mov	ecx, 18
	call	setvect

; 265  : 	setvect(19, simd_fpu_fault);

	lea	rdx, OFFSET FLAT:?simd_fpu_fault@@YAX_KPEAX@Z ; simd_fpu_fault
	mov	ecx, 19
	call	setvect

; 266  : }

	add	rsp, 40					; 00000028H
	ret	0
?x86_64_exception_init@@YAXXZ ENDP			; x86_64_exception_init
_TEXT	ENDS
END
